# Ingredient Sanity Check

***

### Imports

In [1]:
import pandas as pd

In [2]:
ingredients = pd.read_csv("data/preprocessed/Ingredients_List.csv")
items = pd.read_csv("data/preprocessed/Items_List.csv")
preps = pd.read_csv("data/preprocessed/Preps_List.csv")
products = pd.read_csv("data/preprocessed/Products_List.csv")
mapping = pd.read_csv("data/mapping/Mapping.csv")
RESTAURANT_NAME = "SUMMER_CONF"

In [3]:
def get_ingredients(recipe_id):
    """
    Retrieve all ingredients and their quantities for a given recipe.
    This function takes a recipe ID and returns a DataFrame containing all the ingredients
    required for the recipe, along with their quantities. It handles nested ingredients
    by recursively fetching all related ingredients.
    Parameters:
    recipe_id (str): The ID of the recipe for which ingredients are to be retrieved.
    Returns:
    pd.DataFrame: A DataFrame containing the ingredients with their quantities.
    """
    recipe = ingredients[ingredients["Recipe"] == recipe_id]
    def get_all_ingredients(recipe):
        all_ingredients = pd.DataFrame()  # Initialize an empty DataFrame to store all ingredients

        for index, row in recipe.iterrows():
            temp = ingredients[ingredients["Recipe"] == row["IngredientId"]]
            if not temp.empty:
                all_ingredients = pd.concat([all_ingredients, temp, get_all_ingredients(temp)], ignore_index=True)
            all_ingredients = pd.concat([all_ingredients, temp], ignore_index=True)
        
        return pd.concat([recipe, all_ingredients], ignore_index=True)  # Return original recipe with all ingredients

    # Calling the function with the recipe DataFrame
    complete_recipe = get_all_ingredients(recipe)
    recipe_items = []
    recipe_preps = []

    # Seperate into Items and Preps
    items_list = complete_recipe[complete_recipe["IngredientId"].str.startswith("I")]
    items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
    preps_list = complete_recipe[complete_recipe["IngredientId"].str.startswith("P")]
    preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    for index,row in complete_recipe.iterrows():
        temp = items[items["ItemId"] == row["IngredientId"]]
        recipe_items.append(temp)
        temp2 = preps[preps["PrepId"] == row["IngredientId"]]
        recipe_preps.append(temp2)
    
    recipe_items = pd.concat(recipe_items, ignore_index=True)
    recipe_preps = pd.concat(recipe_preps, ignore_index=True)
    recipe_items.drop_duplicates(subset="ItemId", keep="first", inplace=True)
    recipe_preps.drop_duplicates(subset="PrepId", keep="first", inplace=True)
    assert len(recipe_items) == len(items_list)
    recipe_items_with_quants = pd.merge(recipe_items, items_list, left_on="ItemId", right_on="IngredientId")
    recipe_items_with_quants.drop(columns=["IngredientId","CaseQty","CaseUOM","PakQty","PakUOM", "InventoryGroup", "Conversion","InvFactor"], inplace=True)
    return recipe_items_with_quants

In [ ]:
# Initialize a list to store all recipe and ingredient details
data = []

for _, row in products.iterrows():
    # Extract recipe details
    recipe_id = row['ProdId']
    recipe_name = row.get('Description', 'Unknown')
    
    # Get the ingredients for the recipe
    ingres = get_ingredients(row["ProdId"])
    
    for _, ingredient in ingres.iterrows():
        # Filter the mapping for the current ingredient
        item_mapping = mapping[mapping["ItemId"] == ingredient["ItemId"]]
        
        # Safely extract values from item_mapping
        category_id = item_mapping['CategoryID'].iloc[0] if not item_mapping.empty else "Unknown"
        food_category = item_mapping['Food Category_y'].iloc[0] if not item_mapping.empty else "Unknown"
        
        # Append a dictionary with all details to the data list
        data.append({
            "Recipe ID": recipe_id,
            "Recipe Name": recipe_name,
            "Ingredient": ingredient['Description'],
            "Quantity": ingredient['Qty'],
            "Unit": ingredient['Uom'],
            "Category ID": category_id,
            "Emission Category": food_category,
        })
# List of preps to be included
preps_list = []

# # Uncommennt the below code if all preps are to be included
# for index, row in preps.iterrows():
#     preps_list.append(preps.loc[index, 'PrepId'])

for prep in preps_list:
    recipe_id = prep
    try:
        recipe_name = preps[preps["PrepId"] == prep]["Description"].iloc[0]
    except:
        continue

    display(preps[preps["PrepId"] == prep])
    
    # Get the ingredients for the recipe
    ingres = get_ingredients(recipe_id)
    
    for _, ingredient in ingres.iterrows():
        # Filter the mapping for the current ingredient
        item_mapping = mapping[mapping["ItemId"] == ingredient["ItemId"]]
        
        # Safely extract values from item_mapping
        category_id = item_mapping['CategoryID'].iloc[0] if not item_mapping.empty else "Unknown"
        food_category = item_mapping['Food Category_y'].iloc[0] if not item_mapping.empty else "Unknown"
        
        # Append a dictionary with all details to the data list
        data.append({
            "Recipe ID": recipe_id,
            "Recipe Name": recipe_name,
            "Ingredient": ingredient['Description'],
            "Quantity": ingredient['Qty'],
            "Unit": ingredient['Uom'],
            "Category ID": category_id,
            "Emission Category": food_category,
        })

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId              Description  PakQty PakUOM InventoryGroup
0  P-26205  BATCH|Sauteed Mushroom*    4.25     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId                Description  PakQty PakUOM InventoryGroup
1  P-43762  Butter chickpea CHICKPEA*   100.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId         Description  PakQty PakUOM InventoryGroup
2  P-24750  CHOPPED|Cilantro *   500.0      g            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId            Description  PakQty PakUOM InventoryGroup
3  P-62139  CHOPPED|Cilantro|NEW*    42.0      g            NaN

    PrepId              Description  PakQty PakUOM       InventoryGroup
4  P-26188  COOKED||Elbow Macaroni*    1.25     Kg  ZDONT USE OK - PREP

    PrepId              Description  PakQty PakUOM InventoryGroup
5  P-71660  COOKED|CubedHashBrowns*     4.8     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId         Description  PakQty PakUOM InventoryGroup
6  P-73514  COOKED|Fettuccine*    20.0     lb           PREP

    PrepId       Description  PakQty PakUOM InventoryGroup
7  P-73515  COOKED|Linguini*    20.0     lb           PREP

   PrepId              Description  PakQty PakUOM InventoryGroup
8  P-7093  COOKED|Mashed Potatoes*    30.0     Kg           PREP

   PrepId   Description  PakQty PakUOM InventoryGroup
9  P-7438  COOKED|Penne    20.0     Kg           PREP

     PrepId             Description  PakQty PakUOM InventoryGroup
10  P-71662  COOKED|Red skin wedge*     4.8     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId     Description  PakQty PakUOM InventoryGroup
11  P-73512  COOKED|Rotini*    20.0     lb           PREP

     PrepId        Description  PakQty PakUOM InventoryGroup
12  P-73513  COOKED|Spaghetti*    20.0     lb           PREP

     PrepId          Description  PakQty PakUOM InventoryGroup
13  P-51532  COOKED|Stirfry Beef     8.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId         Description  PakQty PakUOM InventoryGroup
14  P-43702  DICED||Carrot|3/4*   11.17     Kg            NaN

     PrepId         Description  PakQty PakUOM InventoryGroup
15  P-41095  DICED||Celery|1/4*    15.0     Kg            NaN

     PrepId            Description  PakQty PakUOM InventoryGroup
16  P-53616  DICED||Jalapeno*Small     0.9     Kg            NaN

     PrepId            Description  PakQty PakUOM InventoryGroup
17  P-38515  DICED||Red Onion 3/4*   11.01     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId             Description  PakQty PakUOM InventoryGroup
18  P-9767  DICED||Red Pepper|3/4*     1.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
19  P-57816  DICED||Sweet Potatoes 3/4"*    0.95     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId   Description  PakQty PakUOM InventoryGroup
20  P-73497  DICED||Tofu*     5.0     Kg            NaN

     PrepId                Description  PakQty PakUOM InventoryGroup
21  P-39167  DICED||Yellow Onion|3/4"*   11.01     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId            Description  PakQty PakUOM InventoryGroup
22  P-45194  DICED||Zucchini|3/4"*     1.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId         Description  PakQty PakUOM InventoryGroup
23  P-41094  DICED|Carrot|1/4"*    10.0     Kg            NaN

     PrepId          Description  PakQty PakUOM InventoryGroup
24  P-50839  DICED|Green Pepper*   800.0      g            NaN

     PrepId              Description  PakQty PakUOM InventoryGroup
25  P-35773  DICED|Green Pepper|3/4"     1.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId             Description  PakQty PakUOM InventoryGroup
26  P-9746  DICED|Jumbo Onion|1/4*     1.0     lb            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId             Description  PakQty PakUOM InventoryGroup
27  P-9748  DICED|Jumbo Onion|3/4*     1.0     lb            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId  Description  PakQty PakUOM InventoryGroup
28  P-50563  DICED|Leek*    0.45     lb            NaN

     PrepId          Description  PakQty PakUOM InventoryGroup
29  P-50552  DICED|Onion Yellow*    23.0     lb            NaN

     PrepId        Description  PakQty PakUOM InventoryGroup
30  P-50837  DICED|Red Pepper*   800.0      g            NaN

    PrepId              Description  PakQty PakUOM InventoryGroup
31  P-9765  DICED|Red Pepper|1/4" *     1.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
32  P-38556  DICED|Yellow Onion|1/4" *    11.4     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId          Description  PakQty PakUOM InventoryGroup
33  P-9757  DICED|Zucchini|1/4*     1.0     lb            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
34  P-50802  DRAINED|Artichoke hearts*     2.0     Kg            NaN

     PrepId         Description  PakQty PakUOM InventoryGroup
35  P-51531  DRAINED|Baby Corn*     1.4     Kg            NaN

     PrepId     Description  PakQty PakUOM InventoryGroup
36  P-38637  DRAINED|Caper*    1.85     Kg            NaN

     PrepId        Description  PakQty PakUOM InventoryGroup
37  P-22248  DRAINED|Chickpea*    2.02     Kg            NaN

     PrepId         Description  PakQty PakUOM InventoryGroup
38  P-28989  DRAINED|Chickpeas*     1.8     Kg           PREP

     PrepId              Description  PakQty PakUOM InventoryGroup
39  P-22249  DRAINED|Corn Whole Baby    1.61     Kg            NaN

     PrepId                  Description  PakQty PakUOM InventoryGroup
40  P-22252  DRAINED|Olive Sliced Black*    1.46     Kg            NaN

     PrepId       Description  PakQty PakUOM InventoryGroup
41  P-50586  GARNISH|Cilantro   800.0      g            NaN

     PrepId          Description  PakQty PakUOM InventoryGroup
42  P-50585  GARNISH|Green Onion   900.0      g            NaN

     PrepId      Description  PakQty PakUOM InventoryGroup
43  P-43693  GLAZE|Meatloaf      2.0      L            NaN

     PrepId      Description  PakQty PakUOM InventoryGroup
44  P-51582  JULIENNE|Carrot    10.5     Kg           PREP

     PrepId               Description  PakQty PakUOM InventoryGroup
45  P-50427  MINCED|Ginger and Garlic   110.0      g            NaN

     PrepId          Description  PakQty PakUOM InventoryGroup
46  P-18907  MIX||Salt & Pepper*     1.5     Kg            NaN

     PrepId                Description  PakQty PakUOM InventoryGroup
47  P-25993  MIX|Salt and Pepper - FT*     6.0     Kg            NaN

     PrepId           Description  PakQty PakUOM       InventoryGroup
48  P-26019  MIX|Salt and Pepper*  1225.0      g  ZDONT USE OK - PREP

     PrepId               Description  PakQty PakUOM InventoryGroup
49  P-10113  PREP||Green Onion|Slice*     1.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

    PrepId         Description  PakQty PakUOM InventoryGroup
50  P-7444  PREP|Garlic Puree*     4.0      L           PREP

    PrepId        Description  PakQty PakUOM InventoryGroup
51  P-9733  PREP|Green Onion*   3.946     Kg            NaN

    PrepId        Description  PakQty PakUOM InventoryGroup
52  P-9745  PREP|Jumbo Onion*    45.6     lb            NaN

     PrepId       Description  PakQty PakUOM InventoryGroup
53  P-56949  PREP|Persiallde*   460.0      g            NaN

    PrepId          Description  PakQty PakUOM InventoryGroup
54  P-6605  PREP|Pureed Garlic*     2.5     Kg           PREP

     PrepId           Description  PakQty PakUOM InventoryGroup
55  P-44641  PREP|Wok Fried Tofu*     4.5     Kg            NaN

     PrepId                     Description  PakQty PakUOM InventoryGroup
56  P-37176  PTN D - PORK SCHNITZEL & GRAVY     1.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
57  P-26020  PUREE||Garlic|Kg - FT*USEME     2.5     Kg           PREP

     PrepId           Description  PakQty PakUOM InventoryGroup
58  P-34880  PUREE||Ginger|OK|KG*     4.8     Kg           PREP

     PrepId    Description  PakQty PakUOM InventoryGroup
59  P-20209  PUREE|Ginger*     2.5     Kg           PREP

     PrepId            Description  PakQty PakUOM InventoryGroup
60  P-10496  PUREE|Ginger|Kg - FT*    3.27     Kg           PREP

     PrepId            Description  PakQty PakUOM InventoryGroup
61  P-56833  PUREE|Thai Red Chili*    0.95     Kg            NaN

     PrepId       Description  PakQty PakUOM InventoryGroup
62  P-50835  SAUCE||Kung Pao*    15.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId            Description  PakQty PakUOM InventoryGroup
63  P-33712  SAUCE|Arrabiata Pork*    16.5      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId     Description  PakQty PakUOM InventoryGroup
64  P-26086  SAUCE|Teriyaki    18.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId      Description  PakQty PakUOM InventoryGroup
65  P-36076  SAUCE|Vindaloo     10.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
66  P-47166  SAUCElCorn Starch Slurry*  1235.0      g            NaN

     PrepId                Description  PakQty PakUOM InventoryGroup
67  P-56557  SAUTE|Ginger Beef Veggie*     6.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId              Description  PakQty PakUOM InventoryGroup
68  P-43704  SC||BATCH|3 Bean Chili*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId           Description  PakQty PakUOM InventoryGroup
69  P-72934  SC||BATCH|Aloo Gobi*    50.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                   Description  PakQty PakUOM InventoryGroup
70  P-75620  SC||BATCH|BBQ Chicken THIGH*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                     Description  PakQty PakUOM InventoryGroup
71  P-71302  SC||BATCH|BBQChickenDRUMSTICK*   115.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                 Description  PakQty PakUOM InventoryGroup
72  P-72907  SC||BATCH|Beef Bourgignon*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                 Description  PakQty PakUOM InventoryGroup
73  P-50006  SC||BATCH|Beef Stroganoff*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
74  P-43715  SC||BATCH|Bo Kho Beef Stew*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
75  P-72579  SC||BATCH|Bolognese|Lentil*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                    Description  PakQty PakUOM InventoryGroup
76  P-67599  SC||BATCH|Broc & CauliGratin*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
77  P-26847  SC||BATCH|Butter chicken*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                    Description  PakQty PakUOM InventoryGroup
78  P-72940  SC||Batch|Cajun ChickenThigh*   115.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
79  P-72902  SC||BATCH|Cajun Cod Bake*   100.0    PTN            NaN

     PrepId                   Description  PakQty PakUOM InventoryGroup
80  P-27310  SC||BATCH|Cheese Tortellini*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                    Description  PakQty PakUOM InventoryGroup
81  P-72911  SC||BATCH|Chicken Cacciatore*   115.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
82  P-54705  SC||BATCH|Chicken Tandoori*   115.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                     Description  PakQty PakUOM InventoryGroup
83  P-67836  SC||BATCH|Chicken Tikka Masala   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
84  P-27316  SC||BATCH|Chili NON Carne    91.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                   Description  PakQty PakUOM InventoryGroup
85  P-73498  SC||BATCH|Coconut Miso Tofu*    52.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                     Description  PakQty PakUOM InventoryGroup
86  P-73320  SC||BATCH|Coconut Salmon Miso*   112.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId              Description  PakQty PakUOM InventoryGroup
87  P-52039  SC||BATCH|Dan Dan Tofu*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId              Description  PakQty PakUOM InventoryGroup
88  P-35540  SC||BATCH|French Toast*     1.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
89  P-75653  SC||BATCH|Ginger*Beef NEW   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                   Description  PakQty PakUOM InventoryGroup
90  P-41079  SC||BATCH|GlazedCarolinaHam*   100.0    PTN          MISC.

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                 Description  PakQty PakUOM InventoryGroup
91  P-72935  SC||BATCH|Jerk ChickThigh*   115.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                 Description  PakQty PakUOM InventoryGroup
92  P-67555  SC||BATCH|KungPao Mushroo*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                 Description  PakQty PakUOM InventoryGroup
93  P-26674  SC||BATCH|KungPaoChicken*    100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId              Description  PakQty PakUOM InventoryGroup
94  P-56712  SC||BATCH|Lentil Curry*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
95  P-27286  SC||BATCH|Mac 'N' Cheese*    50.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                Description  PakQty PakUOM InventoryGroup
96  P-51245  SC||BATCH|Mapo Tofu|Base*    40.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                  Description  PakQty PakUOM InventoryGroup
97  P-72912  SC||BATCH|Mushroom Ravioli*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId                     Description  PakQty PakUOM InventoryGroup
98  P-67288  SC||BATCH|Mushroom Stroganoff*    50.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId         Description  PakQty PakUOM InventoryGroup
99  P-33676  SC||BATCH|Oatmeal*    2.25      L            NaN

      PrepId                     Description  PakQty PakUOM InventoryGroup
100  P-42356  SC||BATCH|Paneer Tikka Masala*    45.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                   Description  PakQty PakUOM InventoryGroup
101  P-41318  SC||BATCH|Pork Cutlet Katsu*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                  Description  PakQty PakUOM InventoryGroup
102  P-72941  SC||BATCH|Roast Beef&Gravy*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                Description  PakQty PakUOM InventoryGroup
103  P-26792  SC||BATCH|Scrambled Eggs*     4.8     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId               Description  PakQty PakUOM InventoryGroup
104  P-72936  SC||BATCH|Shepherds Pie*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId            Description  PakQty PakUOM InventoryGroup
105  P-50389  SC||BATCH|Shoyu Tofu*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                  Description  PakQty PakUOM       InventoryGroup
106  P-26114  SC||BATCH|Smokies&Perogies*   100.0    PTN  ZDONT USE OK - PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                Description  PakQty PakUOM InventoryGroup
107  P-75621  SC||BATCH|squash Ravioli*   100.0    PTN            NaN

      PrepId                     Description  PakQty PakUOM InventoryGroup
108  P-72945  SC||Batch|Teri. Chicken Thigh*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                   Description  PakQty PakUOM InventoryGroup
109  P-72937  SC||BATCH|Thai ChickenThigh*   115.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                  Description  PakQty PakUOM InventoryGroup
110  P-68210  SC||BATCH|Turkey Parmesean*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
111  P-72866  SC||BATCH|Veg Pad Thai*    50.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                    Description  PakQty PakUOM InventoryGroup
112  P-43785  SC||BATCH|Veg Samosa&Chutney*    50.0    PTN            NaN

      PrepId                   Description  PakQty PakUOM InventoryGroup
113  P-71314  SC||BATCHIChickpea Vindaloo*    50.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                   Description  PakQty PakUOM InventoryGroup
114  P-72867  SC||BATCHIPeri Peri Chicken*   100.0   each            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId               Description  PakQty PakUOM InventoryGroup
115  P-26476  SC||BATTER|French Toast*    11.0      L           PREP

      PrepId                Description  PakQty PakUOM InventoryGroup
116  P-49552  SC||BREAKFAST MEAT|Bacon*     1.0    PTN            NaN

      PrepId                     Description  PakQty PakUOM InventoryGroup
117  P-75607  SC||BREAKFAST MEAT|BeyondPatt*     1.0    PTN            NaN

      PrepId                    Description  PakQty PakUOM InventoryGroup
118  P-73358  SC||BREAKFAST MEAT|TurkeySau*     1.0    PTN            NaN

      PrepId                   Description  PakQty PakUOM InventoryGroup
119  P-73359  SC||BREAKFASTMEAT|PorkSausa*     1.0    PTN            NaN

      PrepId                Description  PakQty PakUOM InventoryGroup
120  P-58362  SC||BRINED|Turkey Breast*    25.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                  Description  PakQty PakUOM InventoryGroup
121  P-75608  SC||Carolina Gold BBQ Sauce    20.0      L            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
122  P-73365  SC||COOKED|Basmati*     9.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
123  P-27304  SC||COOKED|Egg Noodles*    20.0     lb           PREP

      PrepId      Description  PakQty PakUOM InventoryGroup
124  P-72823  SC||FRIED|Tofu*    20.0     Kg            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
125  P-71667  SC||GREEK YOGURT*     4.0     Kg            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
126  P-50386  SC||MARINADE|Shoyu*     2.5      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                     Description  PakQty PakUOM InventoryGroup
127  P-72456  SC||MARINADE|TikaMasala|Chick*    13.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

,PrepId,Description,PakQty,PakUOM,InventoryGroup
128,P-34085,SC||MARINATED|Butter Chicken*,10.0,Kg,ZDONT USE OK - PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId            Description  PakQty PakUOM InventoryGroup
129  P-42320  SC||MARINATED|Paneer*     1.2     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId        Description  PakQty PakUOM InventoryGroup
130  P-73445  SC||Mix|Meatloaf*    91.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                 Description  PakQty PakUOM InventoryGroup
131  P-53790  SC||ROASTED|Herbed Turkey*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
132  P-26746  SC||ROASTED|Pork loin*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId               Description  PakQty PakUOM InventoryGroup
133  P-48490  SC||ROASTED|PorkCharSui*   100.0    PTN            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
134  P-25893  SC||ROASTED|Potato*    22.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                    Description  PakQty PakUOM InventoryGroup
135  P-73133  SC||ROASTED|SesGingerChicken*   100.0    PTN            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId       Description  PakQty PakUOM       InventoryGroup
136  P-26200  SC||ROASTED|Yam*     3.0     lb  ZDONT USE OK - PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId          Description  PakQty PakUOM InventoryGroup
137  P-48527  SC||SAUCE|3 Cheese*    25.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
138  P-14535  SC||SAUCE|Alfredo|BASE*    25.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                    Description  PakQty PakUOM InventoryGroup
139  P-49385  SC||SAUCE|Arrabiata*(NOPORK)*    15.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId           Description  PakQty PakUOM InventoryGroup
140  P-6989  SC||SAUCE|Bolognese*    21.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                Description  PakQty PakUOM InventoryGroup
141  P-29315  SC||SAUCE|Butter Chicken*    24.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId            Description  PakQty PakUOM InventoryGroup
142  P-72910  SC||SAUCE|Cacciatore*    27.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                   Description  PakQty PakUOM InventoryGroup
143  P-71432  SC||SAUCE|CauliflowerCheese*     9.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId        Description  PakQty PakUOM InventoryGroup
144  P-40848  SC||SAUCE|Cheese*    11.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
145  P-27301  SC||SAUCE|Chimichurri*     7.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                Description  PakQty PakUOM InventoryGroup
146  P-43631  SC||SAUCE|Chorizo Tomato*    12.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId         Description  PakQty PakUOM InventoryGroup
147  P-44686  SC||SAUCE|Dan Dan*    15.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId       Description  PakQty PakUOM InventoryGroup
148  P-26628  SC||SAUCE|Gravy*    17.0      L           PREP

      PrepId                Description  PakQty PakUOM InventoryGroup
149  P-72938  SC||SAUCE|Mushroom Cream*    14.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
150  P-26771  SC||SAUCE|Onion Gravy*     4.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
151  P-55559  SC||SAUCE|Pad Thai 2.0*    10.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
152  P-42319  SC||SAUCE|Paneer Gravy*    10.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId           Description  PakQty PakUOM InventoryGroup
153  P-54253  SC||SAUCE|Peri Peri*    21.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM       InventoryGroup
154  P-50355  SC||SAUCE|Pesto Cream*    20.0      L  ZDONT USE OK - PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

     PrepId           Description  PakQty PakUOM InventoryGroup
155  P-8164  SC||SAUCE|Primavera*    20.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId            Description  PakQty PakUOM  InventoryGroup
156  P-51922  SC||SAUCE|Puttanesca*    25.0      L  FOOD - GROCERY

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
157  P-44904  SC||SAUCE|Ratatouille*    25.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                    Description  PakQty PakUOM InventoryGroup
158  P-26611  SC||SAUCE|RoastedGarlicCream*    15.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                     Description  PakQty PakUOM InventoryGroup
159  P-15266  SC||SAUCE|SundriedTomatoPesto*     9.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId              Description  PakQty PakUOM InventoryGroup
160  P-72903  SC||SAUCE|Sweet & Sour*    31.0      L           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                     Description  PakQty PakUOM InventoryGroup
161  P-72457  SC||SAUCE|TikkaMasala|Chicken*     8.5      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId               Description  PakQty PakUOM InventoryGroup
162  P-60795  SC||SAUCE|TomSauce|BASE*    18.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                   Description  PakQty PakUOM InventoryGroup
163  P-57631  SC||SKEWER|Souvlaki Chicken      1.0   each            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId          Description  PakQty PakUOM InventoryGroup
164  P-73364  SC||Steamed|Potato*    21.0     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
165  P-71593  SC||STRAWBERRY YOGURT*     2.0     Kg            NaN

      PrepId             Description  PakQty PakUOM InventoryGroup
166  P-72905  SC||Sweet & Sour|Pork*   100.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId             Description  PakQty PakUOM InventoryGroup
167  P-72904  SC||Sweet & Sour|Tofu*    50.0    PTN           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId          Description  PakQty PakUOM InventoryGroup
168  P-71594  SC||VANILLA YOGURT*     1.0     Kg            NaN

      PrepId                  Description  PakQty PakUOM  InventoryGroup
169  P-43729  SC|BATCH|ShoyuChickenThigh*   100.0    PTN  FOOD - GROCERY

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                     Description  PakQty PakUOM InventoryGroup
170  P-25696  SC|BATCHITeriyaki TofuStirfry*     6.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId      Description  PakQty PakUOM InventoryGroup
171  P-73363  SC|Cooked|Rice*     9.0     Kg            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId         Description  PakQty PakUOM InventoryGroup
172  P-34123  SLICED||Onion 1/8*   11.01     Kg           PREP

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId    Description  PakQty PakUOM InventoryGroup
173  P-50619  SLICED|Celery     7.5     Kg            NaN

      PrepId    Description  PakQty PakUOM InventoryGroup
174  P-19209  SLICED|Celery    15.4     Kg            NaN

      PrepId               Description  PakQty PakUOM InventoryGroup
175  P-50840  SLICED|Green Pepper 1/8"   1.764     lb           PREP

      PrepId                  Description  PakQty PakUOM InventoryGroup
176  P-58359  SLICED|Mushroom Foodservice    10.0     lb            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
177  P-50841  SLICED|Zucchini 3/4"   900.0      g            NaN

      PrepId         Description  PakQty PakUOM InventoryGroup
178  P-50495  SLURRY|Cornstarch*     2.0      L            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
179  P-57630  SPICE|Mediterraen   500.0      g            NaN

      PrepId             Description  PakQty PakUOM InventoryGroup
180  P-32673  STOCK||Beef from conc*    32.0      L           PREP

      PrepId              Description  PakQty PakUOM InventoryGroup
181  P-50600  STOCK||Vegetable Asian*    20.0      L            NaN

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId           Description  PakQty PakUOM       InventoryGroup
182  P-32661  STOCK|Veg from Conc*    31.1      L  ZDONT USE OK - PREP

      PrepId       Description  PakQty PakUOM InventoryGroup
183  P-41312  STOCKlAsian Veg*    18.0      L          FEAST

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_8942/2983413275.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preps_list.drop_duplicates(subset="IngredientId", keep="first", inplace=True)

      PrepId                  Description  PakQty PakUOM InventoryGroup
184  P-24529  TP-PREP*CORN STARCH SLURRY*   100.0     ml           PREP

      PrepId         Description  PakQty PakUOM InventoryGroup
185  P-19208  TP|PROCESS CARROT*     8.2     Kg            NaN

      PrepId                    Description  PakQty PakUOM InventoryGroup
186  P-57214  YIELD||Chorizo Meat(uncased)*    0.75     Kg            NaN

      PrepId                   Description  PakQty PakUOM InventoryGroup
187  P-18781  YIELD||Eggplant*process|AAD*    10.0     Kg            NaN

      PrepId                Description  PakQty PakUOM InventoryGroup
188  P-48933  YIELD||Green onion|Fresh*     4.0     Kg            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
189  P-44728  YIELD||Herb|Parsley*    45.0      g            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
190  P-19175  YIELD||Red Onion*     1.6     Kg           PREP

      PrepId           Description  PakQty PakUOM InventoryGroup
191  P-22094  YIELD||Sweet Potato*     8.0     Kg            NaN

      PrepId  Description  PakQty PakUOM InventoryGroup
192  P-41047  YIELD||Yam*     1.9     Kg            NaN

     PrepId   Description  PakQty PakUOM InventoryGroup
193  P-9851  YIELD|Beets*     8.5     Kg            NaN

      PrepId                Description  PakQty PakUOM InventoryGroup
194  P-19177  YIELD|Broccoli|Processed*     6.1     Kg            NaN

     PrepId          Description  PakQty PakUOM InventoryGroup
195  P-9713  YIELD|Carrot Jumbo*    45.0     lb            NaN

      PrepId         Description  PakQty PakUOM InventoryGroup
196  P-20248  YIELD|Cauliflower*     9.0     Kg            NaN

     PrepId                 Description  PakQty PakUOM InventoryGroup
197  P-9720  YIELD|Cauliflower|Florets*    11.0     Kg            NaN

      PrepId    Description  PakQty PakUOM InventoryGroup
198  P-12954  YIELD|Celery*   750.0      g            NaN

      PrepId               Description  PakQty PakUOM InventoryGroup
199  P-62388  YIELD|Cremini Mushrooms*   760.0      g            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
200  P-44652  YIELD|Drained Pickle    11.4     Kg           PREP

      PrepId          Description  PakQty PakUOM InventoryGroup
201  P-51529  YIELD|Green Beans.*   900.0      g            NaN

      PrepId                    Description  PakQty PakUOM InventoryGroup
202  P-57146  YIELD|Green Pepper|Processed*     8.3     Kg            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
203  P-16391  YIELD|Green Peppers*     8.3     Kg            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
204  P-45047  YIELD|Herb|Basil*     0.6     Kg            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
205  P-26514  YIELD|Herb|Cilantro*    55.0      g            NaN

      PrepId       Description  PakQty PakUOM InventoryGroup
206  P-50675  YIELD|Herb|Mint*   300.0      g            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
207  P-51536  YIELD|Herb|Oregano*   325.0      g            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
208  P-44896  YIELD|Herb|Parsley*     0.5     Kg            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
209  P-44901  YIELD|Herb|Rosemary*    0.65     Kg            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
210  P-52036  YIELD|Herb|Thyme*   500.0      g            NaN

      PrepId            Description  PakQty PakUOM InventoryGroup
211  P-50429  YIELD|ItalianParsley*   450.0      g           PREP

      PrepId      Description  PakQty PakUOM InventoryGroup
212  P-56811  YIELD|Jalapeno*     4.0     Kg            NaN

      PrepId             Description  PakQty PakUOM InventoryGroup
213  P-57192  YIELD|Oyster Mushroom*     1.0     Kg            NaN

      PrepId                  Description  PakQty PakUOM InventoryGroup
214  P-43718  YIELD|Pasta|Med Rice Stick*    3.75     Kg           PREP

      PrepId            Description  PakQty PakUOM InventoryGroup
215  P-55427  YIELD|Pepper|Serrano*     1.0     Kg            NaN

      PrepId        Description  PakQty PakUOM InventoryGroup
216  P-56290  YIELD|Red Pepper*   363.2      g            NaN

      PrepId                  Description  PakQty PakUOM InventoryGroup
217  P-18746  YIELD|Red Pepper|Processed*     8.3     Kg           PREP

      PrepId       Description  PakQty PakUOM InventoryGroup
218  P-51537  YIELD|Sage|Herb*    0.65     Kg            NaN

      PrepId                     Description  PakQty PakUOM InventoryGroup
219  P-51524  YIELD|ShitakeMushroom|Trimmed*   870.0      g            NaN

      PrepId                Description  PakQty PakUOM InventoryGroup
220  P-57143  YIELD|Thai Chili Peppers*     0.9     Kg            NaN

      PrepId    Description  PakQty PakUOM InventoryGroup
221  P-20267  YIELD|Turnip*     8.1     Kg            NaN

      PrepId          Description  PakQty PakUOM InventoryGroup
222  P-24452  YIELD|Yellow Onion*   0.408     Kg            NaN

      PrepId            Description  PakQty PakUOM InventoryGroup
223  P-16392  YIELD|Yellow Onions.*     8.9     Kg            NaN

      PrepId           Description  PakQty PakUOM InventoryGroup
224  P-57145  YIELD|Yellow Pepper*     8.3     Kg            NaN

     PrepId      Description  PakQty PakUOM InventoryGroup
225  P-9756  YIELD|Zucchini*     0.9     Kg            NaN

      PrepId       Description  PakQty PakUOM InventoryGroup
226  P-20249  YIELD|Zucchini*.    10.8     Kg            NaN

      PrepId                 Description  PakQty PakUOM InventoryGroup
227  P-71592  YIELDILOAF WHITE 5/8 CLUB*    22.0  slice            NaN

In [5]:
# Create a DataFrame from the collected data
df = pd.DataFrame(data)

Still have to consider that some items will only have 1 item in the recipe because sometimes the item is the product itself

In [6]:
## MANUAL CHECK
# A way to check for items that are not made in house
df[df["Recipe ID"].map(df["Recipe ID"].value_counts()) == 1]

,Recipe ID,Recipe Name,Ingredient,Quantity,Unit,Category ID,Emission Category
23,P-24750,CHOPPED|Cilantro *,HERB CILANTRO BUNCH 30CT,1.00,CT,40.0,other vegetables
24,P-62139,CHOPPED|Cilantro|NEW*,HERB CILANTRO BUNCH 30CT,1.00,CT,40.0,other vegetables
62,P-43702,DICED||Carrot|3/4*,CARROTS JUMBO PEELED US,11.40,Kg,38.0,root vegetables
63,P-41095,DICED||Celery|1/4*,CELERYUS,23.00,Kg,40.0,other vegetables
64,P-53616,DICED||Jalapeno*Small,PEPPERS JALAPENO GREEN 10 LBS,1.00,Kg,40.0,other vegetables
...,...,...,...,...,...,...,...
1382,P-16392,YIELD|Yellow Onions.*,ONIONS YELLOW JUMBO,10.00,Kg,39.0,onions and leeks
1383,P-57145,YIELD|Yellow Pepper*,PEPPERS YELLOW HH BC,10.00,Kg,40.0,other vegetables
1384,P-9756,YIELD|Zucchini*,ZUCCHINI MED FCY MX,1.00,Kg,40.0,other vegetables
1385,P-20249,YIELD|Zucchini*.,ZUCCHINI MED FCY MX,11.36,Kg,40.0,other vegetables
1386,P-71592,YIELDILOAF WHITE 5/8 CLUB*,LOAF WHITE*5/8 CLUBHOUSE,1.00,LOAF,24.0,"wheat/rye (bread, pasta, baked goods)"

In [7]:
# Save the DataFrame to a CSV file
df.to_csv(f"ingredients_{RESTAURANT_NAME}.csv", index=False)
df.to_excel(f"ingredients_{RESTAURANT_NAME}.xlsx", sheet_name="Labels", index=False)
print("Data successfully saved to ingredients_"+RESTAURANT_NAME+".csv")

Data successfully saved to ingredients_SUMMER_CONF.csv