![](ubc_header.png)

# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

****

## Part I: Data Preprocessing

## Set up and Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import glob
import os
import random
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse
from datetime import datetime
from rapidfuzz import process, fuzz
from configparser import ConfigParser

In [2]:
# RUN ONLY ONCE
# os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

****

## Load Data Files

### Set Data File Path

In [3]:
# outlet name
name = "AMS_Gallery_2024_25"

# file paths
filepath_list = glob.glob(os.path.join(os.getcwd(), "data", "raw", name, "*.csv"))
filepath_list.append(glob.glob(os.path.join(os.getcwd(), "data", "archive", "AMS","AMS_Gallery_Data","Gallery_all_years_test_new.csv"))[0])
filepath_list

['/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25/data/raw/AMS_Gallery_2024_25/Gallery_2025S_Prep_Recipe_Detail.csv',
 '/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25/data/raw/AMS_Gallery_2024_25/Gallery_2025S_Menu_Product_Detail.csv',
 '/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25/data/archive/AMS/AMS_Gallery_Data/Gallery_all_years_test_new.csv']

In [4]:
Preps = pd.read_csv(filepath_list[0], skiprows = 1, header=None)
Preps.columns = ["Empty","category_1","category_2", "item_descrip","batch_yield", "total_cost", "Total Cost", "Shelf_Life", "Shelf Lifr", "recipe_uom","recipe_cost", "recipe_uom_2","recipe_cost_2","line_qty","ingre_cost","item_descrip.1","uom"]
Preps = Preps.drop(columns=["Total Cost","Shelf_Life","Shelf Lifr", "category_1", "Empty","recipe_uom","recipe_cost","recipe_uom_2","recipe_cost_2"])
Preps.to_csv("preps.csv", index=False)
Preps

,category_2,item_descrip,batch_yield,total_cost,line_qty,ingre_cost,item_descrip.1,uom
0,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg
1,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.50,$0.0000,Water - Tap,L
2,Beverages - Juice,Raspberry Puree,Batch Yield: 2.000 L,$14.0160,1.00,$14.0160,Raspberries Frozen IQF,Kg
3,Beverages - Juice,Raspberry Puree,Batch Yield: 2.000 L,$14.0160,1.50,$0.0000,Water - Tap,L
4,Beverages - Juice,Strawberry Puree,Batch Yield: 2.000 L,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg
...,...,...,...,...,...,...,...,...
1648,Alcohol - White Wine,Sangria White Tab 2023,Batch Yield: 16.000 L,$109.2348,200.00,$4.7647,Bacardi Light Rum 750mL,ml
1649,Alcohol - White Wine,Sangria White Tab 2023,Batch Yield: 16.000 L,$109.2348,200.00,$5.0881,Meagher's Triple Sec,ml
1650,Alcohol - White Wine,Sangria White Tab 2023,Batch Yield: 16.000 L,$109.2348,3.00,$6.0833,JUICE orange 100% tetra,L
1651,Alcohol - White Wine,Sangria White Tab 2023,Batch Yield: 16.000 L,$109.2348,375.00,$9.6546,Malibu 1.14L,ml
1652,Alcohol - White Wine,Sangria White Tab 2023,Batch Yield: 16.000 L,$109.2348,375.00,$7.4452,Abstract Apricot Brandy 750mL,ml

In [5]:
Items = pd.read_csv(filepath_list[1], skiprows = 1, header=None)
Items.columns = ["Empty","category_1","category_2","Warning","Warning.1", "item_descrip","Empty.1", "drop","drop.1","drop.2","drop.3","drop.4","drop.5","PLU","drop.6","uom","item_descrip.1"]
Items = Items.drop(columns=["category_1","category_2","Warning","Warning.1","Empty","Empty.1","drop","drop.1","drop.2","drop.3","drop.4","drop.5","drop.6"])
Items

             item_descrip    PLU      uom                  item_descrip.1
0     Avocado Toast S2025   1.00       ea        Avocado Toast prep S2025
1     Avocado Toast S2025  10.00        g            Radish-baby assorted
2     Avocado Toast S2025   0.25        g            SPICE SMOKED PAPRIKA
3     Avocado Toast S2025   4.00       ml                    red oil 2024
4     Avocado Toast S2025  15.00       ml                  Bacon oil 2025
..                    ...    ...      ...                             ...
77  HH Chips & Salsa 2023   1.00       ea      HH Chips & Salsa Prep 2023
78         HH Hummus 2023   1.00       ea             HH Hummus Prep 2023
79         HH Hummus 2023   1.00       ea              To Go Cutlery 2023
80         HH ONION RINGS   0.50       lb  ONION RING BTD TEMPURA BEEFEAT
81         HH ONION RINGS   2.00  oz (fl)             ITEM AIOLI CHIPOLTE

[82 rows x 4 columns]

In [6]:
# Gallery
# temp = Items[Items["item_descrip"].str.contains("2024S")]
# temp2 = Items[Items["item_descrip"] == "Vegan Caesar (wrap) 2023"] # Manually Added items
# temp3 = Items[Items["item_descrip"] == "Tofu katsu 2024"] # Manually added items
# Products = pd.concat([temp,temp2,temp3])
# Blue Chip
# Create a boolean mask for rows to drop based on the conditions
mask = (
    Items["item_descrip"].str.contains("tea", case=False) |
    # Items["item_descrip"].str.contains("oz", case=False) |
    Items["item_descrip"].str.contains("latte", case=False) |
    Items["item_descrip"].str.contains("TRAVEL BOX", case=False) |
    Items["item_descrip"].str.contains("OWN CUP DISC", case=False) |
    Items["item_descrip"].str.contains("AMERICANO", case=False) |
    Items["item_descrip"].str.contains("ESPRESSO", case=False) |
    Items["item_descrip"].str.contains("MACCHIATO", case=False) |
    Items["item_descrip"].str.contains("add", case=False) 
)

# Filter the DataFrame to exclude the rows that match the mask
Products = Items[~mask].reset_index(drop=True)

# Display the filtered DataFrame
Products

             item_descrip    PLU      uom                  item_descrip.1
0     Avocado Toast S2025   1.00       ea        Avocado Toast prep S2025
1     Avocado Toast S2025  10.00        g            Radish-baby assorted
2     Avocado Toast S2025   0.25        g            SPICE SMOKED PAPRIKA
3     Avocado Toast S2025   4.00       ml                    red oil 2024
4     Avocado Toast S2025  15.00       ml                  Bacon oil 2025
..                    ...    ...      ...                             ...
77  HH Chips & Salsa 2023   1.00       ea      HH Chips & Salsa Prep 2023
78         HH Hummus 2023   1.00       ea             HH Hummus Prep 2023
79         HH Hummus 2023   1.00       ea              To Go Cutlery 2023
80         HH ONION RINGS   0.50       lb  ONION RING BTD TEMPURA BEEFEAT
81         HH ONION RINGS   2.00  oz (fl)             ITEM AIOLI CHIPOLTE

[82 rows x 4 columns]

In [7]:
list_products = Products["item_descrip"].unique()
with open("list_products.csv", 'w') as f:
    for item in list_products:
        f.write("%s\n" % item)

In [8]:
# Get unique values from the 'item_descrip.2' column in Products
prods = Products["item_descrip.1"].unique()

# Get unique values from the 'item_descrip.1' column in Preps
preps_unique = Preps["item_descrip.1"].unique()

# Filter Preps DataFrame to keep only rows where 'item_descrip' is in 'prods' or 'preps_unique'
Preps = Preps[Preps["item_descrip"].isin(prods) | Preps["item_descrip"].isin(preps_unique)]

# Reset index of Preps DataFrame
Preps = Preps.reset_index(drop=True)
Preps

,category_2,item_descrip,batch_yield,total_cost,line_qty,ingre_cost,item_descrip.1,uom
0,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg
1,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.50,$0.0000,Water - Tap,L
2,Beverages - Juice,Strawberry Puree,Batch Yield: 2.000 L,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg
3,Beverages - Juice,Strawberry Puree,Batch Yield: 2.000 L,$5.5242,1.50,$0.0000,Water - Tap,L
4,Kitchen Supplies,To Go Cutlery 2023,Batch Yield: 1.000 ea,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea
...,...,...,...,...,...,...,...,...
670,Bar Supply,Simple Syrup 2023,Batch Yield: 700.000 ml,$1.1568,440.00,$1.1568,SUGAR GRANULATED FINE,g
671,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.1648,ECO 9x6 Kraft Hinged Container,ea
672,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0480,CUTLERY FORK WOODEN ECO,ea
673,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0463,CUTLERY SPOON WOODEN ECO,ea
674,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0461,CUTLERY KNIFE WOODEN ECO,ea

In [9]:
## Modify this accordingly.
"""
There is not a good solution to this so far but this old items list 
is used to keep track of the items that are already in the database.
This is used to avoid adding the same items again.

TODO: Currently, we are just using the last calculated outlet's data but it would be better to 
come up with a new solution for this
"""
old_items = pd.read_csv(filepath_list[-1])
old_items = old_items.drop(columns=['item_num.2', 'item_num.1'])
old_items

,item_num,item_descrip,pak_physical_yield,pak_uom,pak_uom.1,pak_factored_cost,line_item_num,line_qty,items_comments,item_descrip.1,inv_flag,uom
0,17284,2022 goose & Watermelon bull,1.0,PORT,ea,0.559100,1971,0.25,NaN,LIMES,N,ea
1,17284,2022 goose & Watermelon bull,1.0,PORT,fl oz,1.553600,8228,1.00,NaN,Grey Goose 1.14L,N,fl oz
2,17284,2022 goose & Watermelon bull,1.0,PORT,can,1.920800,15803,1.00,NaN,Red Bull Watermelon,N,can
3,18292,Vegan Caesar wrap 2022,1.0,ea,HEAD,2.466700,5505,0.25,NaN,Lettuce - Romaine,N,HEAD
4,18292,Vegan Caesar wrap 2022,1.0,ea,ml,0.189270,8667,2.00,NaN,ITEM GARLIC MAYO,N,fl oz
...,...,...,...,...,...,...,...,...,...,...,...,...
2153,18049,Yellow Curry Prep Gall.2023,1.0,PORT,g,0.005200,2262,1.00,NaN,SESAME SEEDS,Y,g
2154,18049,Yellow Curry Prep Gall.2023,1.0,PORT,oz,0.003968,14434,80.00,NaN,Potato yellow Med 5lb bag,Y,g
2155,18049,Yellow Curry Prep Gall.2023,1.0,PORT,PORT,0.200000,15477,1.00,NaN,2022 Jasmin rice,Y,PORT
2156,18049,Yellow Curry Prep Gall.2023,1.0,PORT,g,0.005300,15637,20.00,NaN,Whole Green Beans IQF,Y,g
2157,18049,Yellow Curry Prep Gall.2023,1.0,PORT,L,0.157331,17941,8.00,NaN,Porch - Yellow Curry,Y,fl oz

In [10]:
# config = ConfigParser()
# config.read("data/mapping/AMS_data/item_ids.ini")
# id_counter = int(config['base']['id_counter'])
# print(id_counter)

In [11]:
used_ids = []
def assign_ids(df):
    # Preprocessing function
    def preprocess(description):
        description = description.lower()
        description = re.sub(r'\s+', ' ', description).strip()
        description = re.sub(r'[^\w\s]', '', description)
        return description

    # Apply preprocessing
    old_items['Normalized_Description'] = old_items['item_descrip'].apply(preprocess)
    df['Normalized_Description'] = df['item_descrip'].apply(preprocess)

    # Create a mapping from normalized description to item_num
    desc_to_item_num = {row['Normalized_Description']: row['item_num'] for idx, row in old_items.iterrows()}

    # Exact match
    df['item_num'] = df['Normalized_Description'].apply(lambda x: desc_to_item_num.get(x))

    # Fuzzy matching function
    def get_all_matches(description, choices, threshold=80):
        matches = process.extract(description, choices, scorer=fuzz.token_sort_ratio)
        return [match for match in matches if match[1] >= threshold]

    # Apply fuzzy matching where exact match failed
    df['Potential_Matches'] = df['Normalized_Description'].apply(lambda x: get_all_matches(x, desc_to_item_num.keys()))

    # Assign item_num directly if there is exactly one potential match
    def assign_item_num_or_matches(row):
        potential_matches = row['Potential_Matches']
        if potential_matches and len(potential_matches) == 1:
            # Assign the item_num of the single potential match
            return desc_to_item_num.get(potential_matches[0][0])
        else:
            # Keep as None if no match or multiple matches
            return None

    # Apply the function to assign item_num
    df['item_num'] = df.apply(lambda row: assign_item_num_or_matches(row), axis=1)

    # Add the best potential match item_num to Items
    def add_best_potential_match_item_num(row):
        potential_matches = row['Potential_Matches']
        if len(potential_matches) > 1:
            best_match = max(potential_matches, key=lambda x: x[1])
            return desc_to_item_num.get(best_match[0])
        return row['item_num']

    # Update Items to include best potential match item_num if exact match fails
    df['item_num'] = df.apply(lambda row: add_best_potential_match_item_num(row), axis=1)

    # Function to generate unique random item_num
    def generate_unique_random_item_num(existing_nums, start=1000):
        random.seed(42) #DO NOT CHANGE
        while True:
            num = random.randint(start, start + 10000)
            if num not in existing_nums and num not in used_ids:
                used_ids.append(num)
                return num

    # Get the set of used item_nums
    used_item_nums = set(old_items['item_num']).union(set(df['item_num'].dropna()))

    # Assign random item_num for rows without one, ensuring same item_descrip gets same item_num
    unassigned = df[df['item_num'].isna()]
    unique_descriptions = unassigned['Normalized_Description'].unique()

    for desc in unique_descriptions:
        random_num = generate_unique_random_item_num(used_item_nums)
        used_item_nums.add(random_num)
        df.loc[df['Normalized_Description'] == desc, 'item_num'] = random_num

    df["item_num"] = df["item_num"].astype(int)
    df.to_csv("df.csv")
    # Optionally, remove the Potential_Matches column if no longer needed
    df.drop(columns=['Potential_Matches',"Normalized_Description"], inplace=True)
    # Print the result
    return df

In [12]:
Preps = assign_ids(Preps)
Products = assign_ids(Products)

In [13]:
#Ensure 'line_item_num' column exists in Items
Preps['line_item_num'] = 0

# Create a dictionary for quick lookup from old_items
old_items_dict = old_items.set_index('item_descrip.1')['line_item_num'].to_dict()
old_ids = list(set(old_items["line_item_num"].unique()))
ID = old_ids[0]

# Iterate through Items and update line_item_num
for index, row in Preps.iterrows():
    description = row['item_descrip.1']
    if description in old_items_dict:
        Preps.at[index, 'line_item_num'] = old_items_dict[description]
    else:
        while ID in old_ids:
            ID += 1
        old_items_dict[description] = ID
        old_ids.append(ID)
        Preps.at[index, "line_item_num"] = ID

# Output the updated DataFrame
display(Preps)

,category_2,item_descrip,batch_yield,total_cost,line_qty,ingre_cost,item_descrip.1,uom,item_num,line_item_num
0,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg,2824,4099
1,Beverages - Juice,Peach Puree,Batch Yield: 2.000 L,$6.6560,1.50,$0.0000,Water - Tap,L,2824,2640
2,Beverages - Juice,Strawberry Puree,Batch Yield: 2.000 L,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg,1409,4100
3,Beverages - Juice,Strawberry Puree,Batch Yield: 2.000 L,$5.5242,1.50,$0.0000,Water - Tap,L,1409,2640
4,Kitchen Supplies,To Go Cutlery 2023,Batch Yield: 1.000 ea,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea,17297,4101
...,...,...,...,...,...,...,...,...,...,...
670,Bar Supply,Simple Syrup 2023,Batch Yield: 700.000 ml,$1.1568,440.00,$1.1568,SUGAR GRANULATED FINE,g,16844,2367
671,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.1648,ECO 9x6 Kraft Hinged Container,ea,1916,4227
672,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0480,CUTLERY FORK WOODEN ECO,ea,1916,9601
673,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0463,CUTLERY SPOON WOODEN ECO,ea,1916,9599
674,Misc,Misc Extras,Batch Yield: 1.000 ea,$0.3051,1.00,$0.0461,CUTLERY KNIFE WOODEN ECO,ea,1916,9600

In [14]:
def extract_yield_and_uom(batch_yield):
    match = re.search(r'Batch\s*Yield:\s*([\d.]+)\s*(\w+)', batch_yield)
    if match:
        physical_yield = float(match.group(1))
        uom = match.group(2)
        return physical_yield, uom
    else:
        print(f"Error parsing batch_yield '{batch_yield}': pattern not found")
        return None, None

# Apply the function and create new columns
Preps['pak_physical_yield'], Preps['pak_uom'] = zip(*Preps['batch_yield'].apply(extract_yield_and_uom))
Preps = Preps.drop(columns=["batch_yield"])
Preps

,category_2,item_descrip,total_cost,line_qty,ingre_cost,item_descrip.1,uom,item_num,line_item_num,pak_physical_yield,pak_uom
0,Beverages - Juice,Peach Puree,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg,2824,4099,2.0,L
1,Beverages - Juice,Peach Puree,$6.6560,1.50,$0.0000,Water - Tap,L,2824,2640,2.0,L
2,Beverages - Juice,Strawberry Puree,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg,1409,4100,2.0,L
3,Beverages - Juice,Strawberry Puree,$5.5242,1.50,$0.0000,Water - Tap,L,1409,2640,2.0,L
4,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea,17297,4101,1.0,ea
...,...,...,...,...,...,...,...,...,...,...,...
670,Bar Supply,Simple Syrup 2023,$1.1568,440.00,$1.1568,SUGAR GRANULATED FINE,g,16844,2367,700.0,ml
671,Misc,Misc Extras,$0.3051,1.00,$0.1648,ECO 9x6 Kraft Hinged Container,ea,1916,4227,1.0,ea
672,Misc,Misc Extras,$0.3051,1.00,$0.0480,CUTLERY FORK WOODEN ECO,ea,1916,9601,1.0,ea
673,Misc,Misc Extras,$0.3051,1.00,$0.0463,CUTLERY SPOON WOODEN ECO,ea,1916,9599,1.0,ea
674,Misc,Misc Extras,$0.3051,1.00,$0.0461,CUTLERY KNIFE WOODEN ECO,ea,1916,9600,1.0,ea

In [15]:
Products["inv_flag"] = "Y"
Preps["inv_flag"] = "Y"

In [16]:
Preps.to_csv("Preps.csv", index=False)
Products.to_csv("Products.csv", index=False)

### Import Items List

In [17]:
Preps = pd.read_csv("Preps.csv")
Products = pd.read_csv("Products.csv")

In [18]:
Preps = Preps[(Preps["item_descrip.1"] != "ITEM - misc") & (Preps["item_descrip.1"] != "BAG PPR SAND 6x2x9")]
Preps.reset_index(drop=True, inplace=True)
Preps

,category_2,item_descrip,total_cost,line_qty,ingre_cost,item_descrip.1,uom,item_num,line_item_num,pak_physical_yield,pak_uom,inv_flag
0,Beverages - Juice,Peach Puree,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg,2824,4099,2.0,L,Y
1,Beverages - Juice,Peach Puree,$6.6560,1.50,$0.0000,Water - Tap,L,2824,2640,2.0,L,Y
2,Beverages - Juice,Strawberry Puree,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg,1409,4100,2.0,L,Y
3,Beverages - Juice,Strawberry Puree,$5.5242,1.50,$0.0000,Water - Tap,L,1409,2640,2.0,L,Y
4,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea,17297,4101,1.0,ea,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
670,Bar Supply,Simple Syrup 2023,$1.1568,440.00,$1.1568,SUGAR GRANULATED FINE,g,16844,2367,700.0,ml,Y
671,Misc,Misc Extras,$0.3051,1.00,$0.1648,ECO 9x6 Kraft Hinged Container,ea,1916,4227,1.0,ea,Y
672,Misc,Misc Extras,$0.3051,1.00,$0.0480,CUTLERY FORK WOODEN ECO,ea,1916,9601,1.0,ea,Y
673,Misc,Misc Extras,$0.3051,1.00,$0.0463,CUTLERY SPOON WOODEN ECO,ea,1916,9599,1.0,ea,Y
674,Misc,Misc Extras,$0.3051,1.00,$0.0461,CUTLERY KNIFE WOODEN ECO,ea,1916,9600,1.0,ea,Y

In [19]:
# Ensure 'item_num' and 'line_item_num' are strings
Preps = Preps.astype({"item_num": str, "line_item_num": str})

# Get unique descriptions from 'item_descrip'
unique_descriptions = Preps["item_descrip"].unique()

# Iterate over rows to update 'item_num' and 'line_item_num'
for idx, row in Preps.iterrows():
    # Prepend 'P-' if not already present in 'item_num'
    if not row["item_num"].startswith("P-"):
        Preps.at[idx, "item_num"] = "P-" + row["item_num"]
    
for idx, row in Preps.iterrows(): 
    # Update 'line_item_num' based on 'item_descrip'
    if row["item_descrip.1"] in unique_descriptions:
        matching_item_num = Preps.loc[Preps["item_descrip"] == row["item_descrip.1"], "item_num"].values[0]
        print(f"Matching item_num: {matching_item_num}")
        Preps.at[idx, "line_item_num"] = matching_item_num
    else:
        # Prepend 'I-' if not already present in 'line_item_num'
        if not row["line_item_num"].startswith("I-"):
            Preps.at[idx, "line_item_num"] = "I-" + row["line_item_num"]

# Optional: Verify the changes
Preps.head(20)

Matching item_num: P-16571
Matching item_num: P-16571
Matching item_num: P-16855
Matching item_num: P-16571
Matching item_num: P-2519
Matching item_num: P-7912
Matching item_num: P-16221
Matching item_num: P-16862
Matching item_num: P-7924
Matching item_num: P-16221
Matching item_num: P-16855
Matching item_num: P-10674
Matching item_num: P-11125
Matching item_num: P-6881
Matching item_num: P-2307
Matching item_num: P-4733
Matching item_num: P-11125
Matching item_num: P-3045
Matching item_num: P-16221
Matching item_num: P-16222
Matching item_num: P-17037
Matching item_num: P-10674
Matching item_num: P-11125
Matching item_num: P-6881
Matching item_num: P-7201
Matching item_num: P-10674
Matching item_num: P-11125
Matching item_num: P-6881
Matching item_num: P-4527
Matching item_num: P-16855
Matching item_num: P-7912
Matching item_num: P-17305
Matching item_num: P-3664
Matching item_num: P-10891
Matching item_num: P-13736
Matching item_num: P-9785
Matching item_num: P-2424
Matching item_num: P-6811
Matching item_num: P-3677
Matching item_num: P-16221
Matching item_num: P-10863
Matching item_num: P-16855
Matching item_num: P-9928
Matching item_num: P-16855
Matching item_num: P-5012
Matching item_num: P-6811
Matching item_num: P-18381
Matching item_num: P-13736
Matching item_num: P-8428
Matching item_num: P-7216
Matching item_num: P-5422
Matching item_num: P-10980
Matching item_num: P-16575
Matching item_num: P-6820
Matching item_num: P-16748
Matching item_num: P-2169
Matching item_num: P-5010
Matching item_num: P-3803
Matching item_num: P-4598

,category_2,item_descrip,total_cost,line_qty,ingre_cost,item_descrip.1,uom,item_num,line_item_num,pak_physical_yield,pak_uom,inv_flag
0,Beverages - Juice,Peach Puree,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg,P-2824,I-4099,2.0,L,Y
1,Beverages - Juice,Peach Puree,$6.6560,1.50,$0.0000,Water - Tap,L,P-2824,I-2640,2.0,L,Y
2,Beverages - Juice,Strawberry Puree,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg,P-1409,I-4100,2.0,L,Y
3,Beverages - Juice,Strawberry Puree,$5.5242,1.50,$0.0000,Water - Tap,L,P-1409,I-2640,2.0,L,Y
4,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea,P-17297,I-4101,1.0,ea,Y
5,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.1447,LID Foil Board 6x8.5 SO,ea,P-17297,I-4102,1.0,ea,Y
6,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0169,Napkin Bev 2ply White,ea,P-17297,I-4103,1.0,ea,Y
7,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0471,CUTLERY FORK WOOD bulk,ea,P-17297,I-4104,1.0,ea,Y
8,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0471,CUTLERY SPOON WOOD soup,ea,P-17297,I-4105,1.0,ea,Y
9,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.3536,Foil pan 6x8.5 oblong 2.25lb,ea,P-17297,I-4106,1.0,ea,Y
10,Commissary,Catr - Mint Chutney,$9.9625,2.00,$4.0000,CILANTRO 3ct,bunch,P-5506,I-4107,750.0,ml,Y
11,Commissary,Catr - Mint Chutney,$9.9625,10.00,$0.0888,GARLIC WHOLE PEELED,g,P-5506,I-1874,750.0,ml,Y
12,Commissary,Catr - Mint Chutney,$9.9625,100.00,$3.7258,MINT LEAVES,g,P-5506,I-1995,750.0,ml,Y
13,Commissary,Catr - Mint Chutney,$9.9625,1.00,$0.0299,SPICE CUMIN SEED GROUND BOX,g,P-5506,I-2329,750.0,ml,Y
14,Commissary,Catr - Mint Chutney,$9.9625,5.00,$0.0379,Ginger Fresh,g,P-5506,I-2958,750.0,ml,Y
15,Commissary,Catr - Mint Chutney,$9.9625,5.00,$0.0179,SALT KOSHER COARSE,g,P-5506,I-4091,750.0,ml,Y
16,Commissary,Catr - Mint Chutney,$9.9625,500.00,$2.0038,Yogurt Plain 4LTR,ml,P-5506,I-5264,750.0,ml,Y
17,Commissary,Catr - Mint Chutney,$9.9625,10.00,$0.0583,Juice - Lemon Fresh Squeezed,g,P-5506,I-6203,750.0,ml,Y
18,Commissary,Pro - Confit Garlic in Oil,$16.5913,2.50,$10.0750,GARLIC WHOLE PEELED,lb,P-5012,I-1874,2.0,L,Y
19,Commissary,Pro - Confit Garlic in Oil,$16.5913,2.00,$5.4600,PFO OIL CANOLA JIB ANTI FOAM,L,P-5012,I-2119,2.0,L,Y

In [20]:
Preps.dtypes

category_2             object
item_descrip           object
total_cost             object
line_qty               object
ingre_cost             object
item_descrip.1         object
uom                    object
item_num               object
line_item_num          object
pak_physical_yield    float64
pak_uom                object
inv_flag               object
dtype: object

In [21]:
mask_BC = ["NAPKIN DISP 1PLY INTERFOLD KRA", '"9""x6 1/8"" NAT HINGED CONTAINER"', "ECO 9x6 Kraft Hinged Container", 
           "BAG PPR SAND 6x2x9", "CUTLERY SPOON WOODEN ECO", "6x6x3 CLAMSHELL", '"Box - Pizza 10"" Kraft"', '9"x6 1/8" NAT HINGED CONTAINER']
mask_Gallery = ["To Go Cutlery 2023","Misc Extras"]
Products = Products[~Products["item_descrip.1"].isin(mask_BC)]
Products

,item_descrip,PLU,uom,item_descrip.1,item_num,inv_flag
0,Avocado Toast S2025,1.00,ea,Avocado Toast prep S2025,15408,Y
1,Avocado Toast S2025,10.00,g,Radish-baby assorted,15408,Y
2,Avocado Toast S2025,0.25,g,SPICE SMOKED PAPRIKA,15408,Y
3,Avocado Toast S2025,4.00,ml,red oil 2024,15408,Y
4,Avocado Toast S2025,15.00,ml,Bacon oil 2025,15408,Y
...,...,...,...,...,...,...
77,HH Chips & Salsa 2023,1.00,ea,HH Chips & Salsa Prep 2023,17302,Y
78,HH Hummus 2023,1.00,ea,HH Hummus Prep 2023,3340,Y
79,HH Hummus 2023,1.00,ea,To Go Cutlery 2023,3340,Y
80,HH ONION RINGS,0.50,lb,ONION RING BTD TEMPURA BEEFEAT,9016,Y
81,HH ONION RINGS,2.00,oz (fl),ITEM AIOLI CHIPOLTE,9016,Y

In [22]:
#Ensure 'line_item_num' column exists in Items
Products.loc[:,'line_item_num'] = ""

# Create a dictionary for quick lookup from old_items
items_dict = Preps.set_index('item_descrip.1')['line_item_num'].to_dict()
items_dict.update(Preps.set_index('item_descrip')['item_num'].to_dict())

ids = list(set(Preps["line_item_num"].unique()))
ids.extend(Preps["item_num"].unique())
ids = [int(str(id).split("-")[1]) for id in ids]
print(ids)
ID = ids[0]

# Iterate through Items and update line_item_num
for index, row in Products.iterrows():
    description = row['item_descrip.1']
    if description in items_dict:
        Products.at[index, 'line_item_num'] = items_dict[description]
    else:
        while ID in ids:
            ID += 1
        print(row["item_descrip.1"], "not in Preps")
        items_dict[description] = "I-" + str(ID)
        ids.append(ID)
        Products.at[index, "line_item_num"] = "I-" + str(ID)

# Output the updated DataFrame
display(Products)

[3804, 4136, 17129, 5008, 5731, 16748, 2986, 4201, 14530, 17305, 1833, 11125, 4196, 4200, 4116, 4100, 13842, 4220, 4148, 4182, 2087, 4127, 7216, 4598, 4222, 3803, 1982, 4108, 2066, 14978, 14424, 1568, 11829, 2329, 2347, 5264, 13001, 4152, 4103, 4105, 4106, 15547, 1610, 2424, 5422, 14532, 2349, 1917, 4221, 3258, 2378, 17946, 4210, 2086, 2159, 2640, 4109, 4123, 2068, 16571, 2519, 7924, 5777, 1660, 4191, 4135, 4104, 2324, 2446, 4149, 1874, 1958, 4224, 4190, 7980, 5254, 2093, 12764, 2951, 14419, 6881, 12132, 1894, 2257, 14790, 2436, 1995, 2181, 14429, 4185, 4192, 4188, 4733, 4163, 13598, 3045, 12351, 2367, 2307, 4014, 4195, 4112, 2341, 12173, 1782, 10863, 4101, 9117, 4128, 4151, 2323, 4124, 10891, 4111, 4113, 2183, 15554, 4165, 1908, 14126, 4174, 4107, 4150, 10674, 16855, 4118, 17037, 1941, 4197, 6090, 14484, 4129, 4125, 5204, 1892, 2263, 1927, 4147, 4140, 4115, 4121, 4227, 5010, 1689, 2443, 4137, 4175, 6811, 4133, 2238, 4091, 6204, 1978, 4119, 2025, 4167, 10834, 5575, 2209, 13736, 2119, 2153, 4184, 3677, 4120, 4226, 4170, 14423, 2920, 16222, 2169, 3180, 1588, 12361, 4110, 7201, 1655, 1789, 2402, 2243, 4205, 4099, 14422, 4181, 9785, 1859, 2339, 1635, 5803, 4114, 9601, 4141, 6865, 4208, 9600, 5773, 2366, 4144, 16862, 15200, 8428, 12212, 16221, 14127, 5095, 9928, 16575, 4161, 18051, 7912, 14418, 5012, 7645, 5075, 2464, 16224, 8975, 4102, 4126, 4132, 4171, 8851, 3664, 6203, 4138, 7338, 2400, 1649, 7656, 4178, 4183, 5941, 4225, 4166, 3005, 2958, 1783, 2037, 4189, 4219, 2121, 4223, 4117, 10980, 7647, 4527, 4143, 4217, 1924, 3147, 9599, 2203, 4214, 6820, 11704, 18381, 2824, 1409, 17297, 5506, 5012, 6068, 6811, 4657, 3286, 17360, 16778, 17366, 18334, 16855, 18349, 2679, 9935, 11706, 16794, 17013, 2424, 18274, 16221, 16222, 16571, 11125, 16793, 18268, 10674, 16860, 7912, 18329, 16780, 16856, 1520, 1488, 2535, 4582, 4811, 9279, 10863, 1434, 10195, 4257, 9928, 7873, 14827, 4611, 8359, 10654, 5557, 1106, 3615, 7924, 6574, 13736, 18052, 17302, 17301, 17305, 17303, 5552, 3547, 4527, 6514, 2674, 2519, 7224, 2584, 6881, 6635, 10891, 5333, 1711, 8527, 9785, 3045, 7201, 2291, 10044, 15007, 5803, 6925, 10459, 4150, 2139, 1750, 4733, 5741, 2307, 4814, 16862, 18336, 18380, 12209, 17037, 18381, 18470, 2654, 17486, 7227, 5554, 8428, 16748, 6977, 3664, 7065, 6820, 4432, 5374, 2169, 10980, 3803, 9751, 5010, 16575, 3677, 8573, 7216, 5422, 10125, 4598, 6313, 15368, 16844, 1916]
PUMPKIN SEEDS not in Preps
SHRIMP Butterfly Coconut 13-15 not in Preps
Bean Vermiceli Noodle Fortune  not in Preps
Lettuce Green Leaf Fillet not in Preps
SPICE Piri Piri seasoning mix not in Preps
ONION RING BTD TEMPURA BEEFEAT not in Preps

,item_descrip,PLU,uom,item_descrip.1,item_num,inv_flag,line_item_num
0,Avocado Toast S2025,1.00,ea,Avocado Toast prep S2025,15408,Y,P-2535
1,Avocado Toast S2025,10.00,g,Radish-baby assorted,15408,Y,I-4143
2,Avocado Toast S2025,0.25,g,SPICE SMOKED PAPRIKA,15408,Y,I-12361
3,Avocado Toast S2025,4.00,ml,red oil 2024,15408,Y,P-2291
4,Avocado Toast S2025,15.00,ml,Bacon oil 2025,15408,Y,P-4582
...,...,...,...,...,...,...,...
77,HH Chips & Salsa 2023,1.00,ea,HH Chips & Salsa Prep 2023,17302,Y,P-17302
78,HH Hummus 2023,1.00,ea,HH Hummus Prep 2023,3340,Y,P-17305
79,HH Hummus 2023,1.00,ea,To Go Cutlery 2023,3340,Y,P-17297
80,HH ONION RINGS,0.50,lb,ONION RING BTD TEMPURA BEEFEAT,9016,Y,I-3810
81,HH ONION RINGS,2.00,oz (fl),ITEM AIOLI CHIPOLTE,9016,Y,I-4152

### Extracting all Preps

In [23]:
# Filter the DataFrame to include only rows where 'item_num' starts with 'P-'
Preperations = Preps.copy()

# Select specific columns from the filtered DataFrame
Preperations = Preperations[['item_num', 'item_descrip', 'pak_physical_yield', 'pak_uom', 'inv_flag']]
Preperations.rename(columns={'item_num': 'PrepId', 'item_descrip': 'Description', 'pak_physical_yield': 'PakQty', 'pak_uom': 'PakUOM', 'inv_flag': 'InventoryGroup'}, inplace=True)
Preperations.drop_duplicates(subset=["PrepId"], inplace=True)
Preperations.reset_index(drop=True, inplace=True)
Preperations

      PrepId                 Description  PakQty PakUOM InventoryGroup
0     P-2824                 Peach Puree     2.0      L              Y
1     P-1409            Strawberry Puree     2.0      L              Y
2    P-17297          To Go Cutlery 2023     1.0     ea              Y
3     P-5506         Catr - Mint Chutney   750.0     ml              Y
4     P-5012  Pro - Confit Garlic in Oil     2.0      L              Y
..       ...                         ...     ...    ...            ...
121   P-4598                Veggie Stock     6.0     Kg              Y
122   P-6313                     Waffles    55.0     ea              Y
123  P-15368        Pro - Marinara Sauce     7.0      L              Y
124  P-16844           Simple Syrup 2023   700.0     ml              Y
125   P-1916                 Misc Extras     1.0     ea              Y

[126 rows x 5 columns]

In [24]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Preps_List.csv")
Preperations.to_csv(path, index = False, header = True)

### Extracting all Items

In [25]:
Preps

,category_2,item_descrip,total_cost,line_qty,ingre_cost,item_descrip.1,uom,item_num,line_item_num,pak_physical_yield,pak_uom,inv_flag
0,Beverages - Juice,Peach Puree,$6.6560,1.00,$6.6560,FRUIT peach slice IQF,Kg,P-2824,I-4099,2.0,L,Y
1,Beverages - Juice,Peach Puree,$6.6560,1.50,$0.0000,Water - Tap,L,P-2824,I-2640,2.0,L,Y
2,Beverages - Juice,Strawberry Puree,$5.5242,1.00,$5.5242,Strawberries IQF FRZ,Kg,P-1409,I-4100,2.0,L,Y
3,Beverages - Juice,Strawberry Puree,$5.5242,1.50,$0.0000,Water - Tap,L,P-1409,I-2640,2.0,L,Y
4,Kitchen Supplies,To Go Cutlery 2023,$0.6308,1.00,$0.0214,CUP PORT PAPER WHT 2Z,ea,P-17297,I-4101,1.0,ea,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
670,Bar Supply,Simple Syrup 2023,$1.1568,440.00,$1.1568,SUGAR GRANULATED FINE,g,P-16844,I-2367,700.0,ml,Y
671,Misc,Misc Extras,$0.3051,1.00,$0.1648,ECO 9x6 Kraft Hinged Container,ea,P-1916,I-4227,1.0,ea,Y
672,Misc,Misc Extras,$0.3051,1.00,$0.0480,CUTLERY FORK WOODEN ECO,ea,P-1916,I-9601,1.0,ea,Y
673,Misc,Misc Extras,$0.3051,1.00,$0.0463,CUTLERY SPOON WOODEN ECO,ea,P-1916,I-9599,1.0,ea,Y
674,Misc,Misc Extras,$0.3051,1.00,$0.0461,CUTLERY KNIFE WOODEN ECO,ea,P-1916,I-9600,1.0,ea,Y

In [26]:
Products[~Products['line_item_num'].str.startswith('P-')].head()

,item_descrip,PLU,uom,item_descrip.1,item_num,inv_flag,line_item_num
1,Avocado Toast S2025,10.00,g,Radish-baby assorted,15408,Y,I-4143
2,Avocado Toast S2025,0.25,g,SPICE SMOKED PAPRIKA,15408,Y,I-12361
5,Avocado Toast S2025,0.25,ea,BACON SLCD RAW 16-18ct,15408,Y,I-4135
6,Avocado Toast S2025,4.00,g,PUMPKIN SEEDS,15408,Y,I-3805
7,Avocado Toast S2025,0.02,bunch,PARSLEY,15408,Y,I-2087

In [27]:
# Filter out rows where 'line_item_num' does not start with 'P-'
temp1 = Preps[~Preps['line_item_num'].str.startswith('P-')]

# Select relevant columns
temp1 = temp1[['line_item_num', 'item_descrip.1', 'line_qty', 'uom', 'pak_physical_yield', 'pak_uom', 'inv_flag']]

temp2 = Products[~Products['line_item_num'].str.startswith('P-')]

temp2 = temp2[['line_item_num', 'item_descrip.1', 'PLU', 'uom', 'inv_flag']]
temp2.rename(columns={'PLU': 'line_qty'}, inplace=True)

items = pd.concat([temp1, temp2], ignore_index=True)

# Rename columns for clarity
items.rename(columns={
    'line_item_num': 'ItemId',
    'item_descrip.1': 'Description',
    'line_qty': 'CaseQty',
    'uom': 'CaseUOM',
    'pak_physical_yield': 'PakQty',
    'pak_uom': 'PakUOM',
    'inv_flag': 'InventoryGroup'
}, inplace=True)

# Define a function to deal with commas in numeric fields
def dealWithComma(x):
    if isinstance(x, str):
        return x.replace(",", "")
    return x

# Apply the function to the 'CaseQty' column
items['CaseQty'] = items['CaseQty'].apply(dealWithComma)

# Convert 'CaseQty' to float
items = items.astype({"CaseQty": float})

# Remove duplicates based on 'ItemId'
items.drop_duplicates(subset=["ItemId"], inplace=True)

# Reset index for the final DataFrame
items.reset_index(drop=True, inplace=True)

# Display the resulting DataFrame
items

,ItemId,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4099,FRUIT peach slice IQF,1.0,Kg,2.0,L,Y
1,I-2640,Water - Tap,1.5,L,2.0,L,Y
2,I-4100,Strawberries IQF FRZ,1.0,Kg,2.0,L,Y
3,I-4101,CUP PORT PAPER WHT 2Z,1.0,ea,1.0,ea,Y
4,I-4102,LID Foil Board 6x8.5 SO,1.0,ea,1.0,ea,Y
...,...,...,...,...,...,...,...
217,I-3806,SHRIMP Butterfly Coconut 13-15,175.0,g,NaN,NaN,Y
218,I-3807,Bean Vermiceli Noodle Fortune,6.0,g,NaN,NaN,Y
219,I-3808,Lettuce Green Leaf Fillet,50.0,g,NaN,NaN,Y
220,I-3809,SPICE Piri Piri seasoning mix,20.0,g,NaN,NaN,Y
221,I-3810,ONION RING BTD TEMPURA BEEFEAT,0.5,lb,NaN,NaN,Y

In [28]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Items_List.csv")
items.to_csv(path, index = False, header = True)

### Extracting all Ingredients

In [29]:
# Ensure 'item_num' and 'line_item_num' columns are strings
Products = Products.astype({"item_num": str, "line_item_num": str})

# Prepend "R-" to 'item_num' column
Products['item_num'] = "R-" + Products['item_num']

# Display the modified DataFrame
Products

,item_descrip,PLU,uom,item_descrip.1,item_num,inv_flag,line_item_num
0,Avocado Toast S2025,1.00,ea,Avocado Toast prep S2025,R-15408,Y,P-2535
1,Avocado Toast S2025,10.00,g,Radish-baby assorted,R-15408,Y,I-4143
2,Avocado Toast S2025,0.25,g,SPICE SMOKED PAPRIKA,R-15408,Y,I-12361
3,Avocado Toast S2025,4.00,ml,red oil 2024,R-15408,Y,P-2291
4,Avocado Toast S2025,15.00,ml,Bacon oil 2025,R-15408,Y,P-4582
...,...,...,...,...,...,...,...
77,HH Chips & Salsa 2023,1.00,ea,HH Chips & Salsa Prep 2023,R-17302,Y,P-17302
78,HH Hummus 2023,1.00,ea,HH Hummus Prep 2023,R-3340,Y,P-17305
79,HH Hummus 2023,1.00,ea,To Go Cutlery 2023,R-3340,Y,P-17297
80,HH ONION RINGS,0.50,lb,ONION RING BTD TEMPURA BEEFEAT,R-9016,Y,I-3810
81,HH ONION RINGS,2.00,oz (fl),ITEM AIOLI CHIPOLTE,R-9016,Y,I-4152

In [30]:
Ingredients = Products[['line_item_num', 'PLU', 'uom', 'item_num']].copy()

Ingredients.rename(columns={'line_item_num': 'IngredientId', 'PLU': 'Qty', 'uom': 'Uom', 'item_num': 'Recipe'}, inplace=True)

Ingredients.drop_duplicates(subset=["IngredientId", "Recipe"], inplace=True)

Ingredients.reset_index(drop=True, inplace=True)
Ingredients

   IngredientId    Qty      Uom   Recipe
0        P-2535   1.00       ea  R-15408
1        I-4143  10.00        g  R-15408
2       I-12361   0.25        g  R-15408
3        P-2291   4.00       ml  R-15408
4        P-4582  15.00       ml  R-15408
..          ...    ...      ...      ...
77      P-17302   1.00       ea  R-17302
78      P-17305   1.00       ea   R-3340
79      P-17297   1.00       ea   R-3340
80       I-3810   0.50       lb   R-9016
81       I-4152   2.00  oz (fl)   R-9016

[82 rows x 4 columns]

In [31]:
temp = Preps[['line_item_num', 'item_num', 'line_qty', 'uom']].copy()
temp.rename(columns={'line_item_num': 'IngredientId', 'item_num': 'Recipe', 'line_qty': 'Qty', 'uom': 'Uom'}, inplace=True)
temp.drop_duplicates(subset=["IngredientId", "Recipe"], inplace=True)
temp.reset_index(drop=True, inplace=True)
temp

    IngredientId   Recipe     Qty Uom
0         I-4099   P-2824    1.00  Kg
1         I-2640   P-2824    1.50   L
2         I-4100   P-1409    1.00  Kg
3         I-2640   P-1409    1.50   L
4         I-4101  P-17297    1.00  ea
..           ...      ...     ...  ..
661       I-2367  P-16844  440.00   g
662       I-4227   P-1916    1.00  ea
663       I-9601   P-1916    1.00  ea
664       I-9599   P-1916    1.00  ea
665       I-9600   P-1916    1.00  ea

[666 rows x 4 columns]

In [32]:
df = [Ingredients, temp]
Ingredients = pd.concat(df)

Ingredients["Qty"] = Ingredients["Qty"].apply(dealWithComma)

In [33]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Ingredients_List.csv")
Ingredients.to_csv(path, index = False, header = True)

### Extracting Products List

In [34]:
Products = Products[['item_num', 'item_descrip', 'inv_flag']]

Products.rename(columns={'item_num': 'ProdId', 'item_descrip': 'Description', 'inv_flag': 'SalesGroup'}, inplace=True)
Products.drop_duplicates(inplace=True)
Products.reset_index(drop=True, inplace=True)
Products

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_1881/4244662357.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Products.rename(columns={'item_num': 'ProdId', 'item_descrip': 'Description', 'inv_flag': 'SalesGroup'}, inplace=True)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_1881/4244662357.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Products.drop_duplicates(inplace=True)

     ProdId                     Description SalesGroup
0   R-15408             Avocado Toast S2025          Y
1    R-4752                   Banh mi S2025          Y
2    R-1525             Banh mi vegan S2025          Y
3   R-14827         Cauliflower taco S 2025          Y
4    R-6168                  Ceviche S 2025          Y
5    R-7572             Chicken taco S 2025          Y
6    R-5386           Coconut shrimp S 2025          Y
7    R-2084           Fish and Chips S 2025          Y
8   R-15511                Fish taco S 2025          Y
9    R-4456                Korean BBQ W2025          Y
10  R-10292  Lemongrass chicken plate S2025          Y
11   R-6155              Carrot Salad S2025          Y
12   R-4483            Fries regular S 2025          Y
13   R-9179        Fries with cheese S 2025          Y
14   R-7482      Fries with PiriPiri S 2025          Y
15  R-17303            HH Spring Rolls 2023          Y
16   R-8517     HH Bottom seared Gyoza 2025          Y
17  R-17302           HH Chips & Salsa 2023          Y
18   R-3340                  HH Hummus 2023          Y
19   R-9016                  HH ONION RINGS          Y

In [35]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Products_List.csv")
Products.to_csv(path, index = False, header = True)

### Import Conversions List

In [36]:
# Read conventions.xml files in the filepath_list and construct a dataframe
ConversionId = []
Multiplier = []
ConvertFromQty = []
ConvertFromUom = []
ConvertToQty = []
ConvertToUom = []

# From the XML file for Conversions append the id into ConversionId, multiplier into Multiplier, ConvertFrom->qty into 
# ConvertFromQty,ConvertFrom->uom into ConvertFromUom, ConvertTo->qty into ConvertToQty and and ConvertTo->uom into the
# CovertToUom list. 
# Make a dataframe out of the 3 lists
# Then also drop the duplicates in the Products dataframe

filepath_list = glob.glob(os.path.join(os.getcwd(), "data", "archive", "OK", "OK 23-24 Sep-Dec*", "*.oc"))
for filepath in filepath_list:
    path = filepath + '/Conversions.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Conversion'):
            ConversionId.append(x.attrib['id'])
            Multiplier.append(x.attrib['multiplier'])
            ConvertFromQty.append(x.find('ConvertFrom').attrib['qty'])
            ConvertFromUom.append(x.find('ConvertFrom').attrib['uom'])
            ConvertToQty.append(x.find('ConvertTo').attrib['qty'])
            ConvertToUom.append(x.find('ConvertTo').attrib['uom'])
    
    
Conversions = pd.DataFrame({'ConversionId': ConversionId, 'Multiplier': Multiplier, 'ConvertFromQty': ConvertFromQty,
                           'ConvertFromUom': ConvertFromUom, 'ConvertToQty': ConvertToQty, 'ConvertToUom': ConvertToUom}
                          ).drop_duplicates()

Conversions.reset_index(drop=True, inplace=True)

In [37]:
Conversions.loc[Conversions["ConversionId"] == "I-29389"]

Empty DataFrame
Columns: [ConversionId, Multiplier, ConvertFromQty, ConvertFromUom, ConvertToQty, ConvertToUom]
Index: []

In [38]:
# all_id_list = Items["ItemId"].unique()
all_id_set = set(Preps["item_num"].unique())
all_conv_set = set(Conversions["ConversionId"].unique())

missing_conv_id = all_id_set - all_conv_set
n = len(missing_conv_id)
print(f"{n} Items in Items dataframe but not in Conversions Dataframe:\n",)
print(missing_conv_id)

126 Items in Items dataframe but not in Conversions Dataframe:

{'P-12209', 'P-17366', 'P-16748', 'P-17305', 'P-11125', 'P-1488', 'P-3547', 'P-7216', 'P-4598', 'P-3803', 'P-1434', 'P-4257', 'P-7227', 'P-10195', 'P-18268', 'P-3615', 'P-4150', 'P-5422', 'P-1409', 'P-2424', 'P-16780', 'P-16793', 'P-3286', 'P-2674', 'P-16571', 'P-7924', 'P-2519', 'P-10044', 'P-18470', 'P-4657', 'P-18334', 'P-14827', 'P-1106', 'P-17486', 'P-15007', 'P-17303', 'P-7065', 'P-6881', 'P-7224', 'P-5333', 'P-9935', 'P-17013', 'P-2291', 'P-4733', 'P-3045', 'P-2307', 'P-4432', 'P-16778', 'P-16860', 'P-10863', 'P-10125', 'P-4582', 'P-10891', 'P-1916', 'P-10674', 'P-6574', 'P-16855', 'P-17037', 'P-5506', 'P-2824', 'P-16856', 'P-1711', 'P-2654', 'P-5554', 'P-5010', 'P-6811', 'P-4814', 'P-9751', 'P-6068', 'P-13736', 'P-7873', 'P-11706', 'P-6635', 'P-6925', 'P-8573', 'P-4611', 'P-4811', 'P-3677', 'P-16222', 'P-2169', 'P-5552', 'P-5374', 'P-16794', 'P-5741', 'P-7201', 'P-18380', 'P-16844', 'P-8527', 'P-18349', 'P-9785', 'P-1750', 'P-18336', 'P-1520', 'P-2139', 'P-8428', 'P-16862', 'P-5803', 'P-18052', 'P-16221', 'P-9928', 'P-16575', 'P-5012', 'P-7912', 'P-9279', 'P-17302', 'P-10459', 'P-15368', 'P-8359', 'P-2584', 'P-17301', 'P-18329', 'P-3664', 'P-10654', 'P-6514', 'P-2535', 'P-2679', 'P-18274', 'P-6977', 'P-10980', 'P-17360', 'P-17297', 'P-4527', 'P-6313', 'P-5557', 'P-6820', 'P-18381'}

In [39]:
Conversions.shape

(444, 6)

In [40]:
Conversions.dtypes

ConversionId      object
Multiplier        object
ConvertFromQty    object
ConvertFromUom    object
ConvertToQty      object
ConvertToUom      object
dtype: object

In [41]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Conversions_List.csv")
Conversions.to_csv(path, index = False, header = True)

In [42]:
temp_df = []
for _,row in Ingredients.iterrows():
    if row["Recipe"] in Products["ProdId"].unique():
        temp_df.append(row)
Products_Recipe = pd.DataFrame(temp_df)
Ingredients_temp = Ingredients[Ingredients["Recipe"].isin(Products_Recipe["IngredientId"].unique())]
temp = pd.concat([Ingredients_temp, Products_Recipe])
Ingredients_temp = Ingredients[Ingredients["Recipe"].isin(temp["IngredientId"].unique())]
temp = pd.concat([Ingredients_temp, temp])
Ingredients = temp
Ingredients

   IngredientId   Qty      Uom   Recipe
4        I-4101  1.00       ea  P-17297
5        I-4102  1.00       ea  P-17297
6        I-4103  1.00       ea  P-17297
7        I-4104  1.00       ea  P-17297
8        I-4105  1.00       ea  P-17297
..          ...   ...      ...      ...
77      P-17302   1.0       ea  R-17302
78      P-17305   1.0       ea   R-3340
79      P-17297   1.0       ea   R-3340
80       I-3810   0.5       lb   R-9016
81       I-4152   2.0  oz (fl)   R-9016

[577 rows x 4 columns]

In [43]:
items = items[items["ItemId"].isin(Ingredients["IngredientId"].unique())]
Preperations = Preperations[Preperations["PrepId"].isin(Ingredients["Recipe"].unique())]

In [44]:
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Ingredients_List.csv")
Ingredients.to_csv(path, index = False, header = True)
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Items_List.csv")
items.to_csv(path, index = False, header = True)
path = os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Preps_List.csv")
Preperations.to_csv(path, index = False, header = True)

***
## Data Summary

In [45]:
# Summary of raw data imported for evaluation
# Here we have a summary of the number of items, preps, ingredients, products, conversions

datasum = pd.DataFrame([items.shape, Preperations.shape, Ingredients.shape, Products.shape, Conversions.shape],
                       columns = ['count', 'columns'], 
                       index = ['Items', 'Preps', 'Ingredients', 'Products', 'Conversions'])
datasum

             count  columns
Items          134        7
Preps           54        5
Ingredients    577        4
Products        20        3
Conversions    444        6