# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

****

## Part II: Data Cleaning

## Set up and Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse
from datetime import datetime

In [2]:
# RUN ONLY ONCE
# os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

***

## Import Preprocessed Datasets

In [3]:
"""
INPUT: a Dataframe
OUPUT: NONE
Description: Prints a description of the datasets
"""
def DescribeDataset(df):
    print(df.dtypes)
    print("\nShape: ", df.shape)
    display(df.head())

In [4]:
# Reading csv file: data/preprocessed/AMS_data/Items_List.csv
Items = pd.read_csv(os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Items_List.csv"))
DescribeDataset(Items)

ItemId             object
Description        object
CaseQty           float64
CaseUOM            object
PakQty            float64
PakUOM             object
InventoryGroup     object
dtype: object

Shape:  (13, 7)

,ItemId,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4212,Fries Wedge Savory Supercrisp,2.0,bag,22.0,ea,Y
1,I-2119,PFO OIL CANOLA JIB ANTI FOAM,250.0,ml,1.2,Kg,Y
2,I-4163,HALAL- Chk Leg B/less SkinON,10.0,LBS,20.0,PORT,Y
3,I-1635,BUTTERMILK 3.25%,2300.0,ml,36.0,ea,Y
4,I-4184,SAUCE RED HOT,20.0,ml,1.0,L,Y

In [5]:
# Read Ingredients_List.csv
Ingredients = pd.read_csv(os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Ingredients_List.csv"))
DescribeDataset(Ingredients)

IngredientId     object
Qty             float64
Uom              object
Recipe           object
dtype: object

Shape:  (18, 4)

  IngredientId    Qty  Uom   Recipe
0      P-10125    1.0   ea  R-10977
1       P-7216    1.0   ea  R-10977
2       I-4212  250.0    g  R-10977
3       I-2119  150.0   ml  R-10977
4       I-4163   10.0  LBS  P-10125

In [6]:
# Read Preps_List.csv
Preps = pd.read_csv(os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Preps_List.csv"))
DescribeDataset(Preps)

PrepId             object
Description        object
PakQty            float64
PakUOM             object
InventoryGroup     object
dtype: object

Shape:  (2, 5)

    PrepId                Description  PakQty PakUOM InventoryGroup
0  P-10125  Club - Buttermilk Chicken    22.0     ea              Y
1   P-7216      Club - Banana Ketchup    10.0   PORT              Y

In [7]:
# Read Product_List.csv that was created from 1_data preprocessing
Products = pd.read_csv(os.path.join(os.getcwd(), "data", "preprocessed", "AMS_data", "Products_List.csv"))
DescribeDataset(Products)

ProdId         object
Description    object
SalesGroup     object
dtype: object

Shape:  (1, 3)

    ProdId            Description SalesGroup
0  R-10977  Club - B.milk Chicken          Y

In [8]:
# Read Coversions_List.csv that was created from 1_data preprocessing
Conversions = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Conversions_Added.csv"))
Conversions.dtypes

ConversionId       object
Multiplier        float64
ConvertFromQty    float64
ConvertFromUom     object
ConvertToQty      float64
ConvertToUom       object
dtype: object

In [9]:
Conversions.head()

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-4226,0.002205,50.00,LBS,22679.50,g
1,I-1971,0.014925,0.25,ea,16.75,g
2,I-15803,0.004000,1.00,can,250.00,ml
3,I-5505,0.005051,0.25,HEAD,49.50,g
4,I-11706,0.008547,1.00,ea,117.00,g

In [10]:
Conversions.shape

(225, 6)

***
## Update Conversion List

In [11]:
# Add the specific conversion info from the newly-processed data to a unit conversion database
Update_Conv = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "AMS_data", "Conv_UpdateConv.csv"))
Update_Conv

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-1971,0.014925,0.25,ea,16.750,g
1,I-15803,0.004000,1.00,can,250.000,ml
2,I-5505,0.005051,0.25,HEAD,49.500,g
3,I-11706,0.008547,1.00,ea,117.000,g
4,I-13308,0.024540,1.00,ea,40.750,g
...,...,...,...,...,...,...
221,I-10834,0.001102,1.00,ea,907.185,g
222,I-4253,0.000352,6.00,can,17040.000,g
223,I-12362,0.010000,0.50,ea,50.000,g
224,I-12363,0.010000,0.50,ea,50.000,g
225,I-12364,0.010000,1.00,ea,100.000,g

In [12]:
# return dataframe with null values
# There are no null values
subset_conv = Update_Conv[Update_Conv["Multiplier"].isna()]
subset_conv

Empty DataFrame
Columns: [ConversionId, Multiplier, ConvertFromQty, ConvertFromUom, ConvertToQty, ConvertToUom]
Index: []

In [13]:
# takes a data frame and assigns a new column called Multiplier to the dataframe
# uses iterrows() to iterate through the rows.Then subset_conv will have a new column named Multiplier with the computed values.
def assign_multiplier(df):
    for ind, row in df.iterrows():
        if row["ConvertFromQty"] == 0 or row["ConvertToQty"] == 0:
            df.loc[ind, "Multiplier"] = 1
        else:
            df.loc[ind, "Multiplier"] = row["ConvertFromQty"] / row["ConvertToQty"]
        
assign_multiplier(subset_conv)

# May 8th change: We want to 
assign_multiplier(Update_Conv)
#subset_conv

In [14]:
# convert dataframe to csv file
Update_Conv = pd.concat([Update_Conv, subset_conv], axis=0)
Update_Conv.to_csv("data/cleaning/update/AMS_data/Conv_UpdateConv.csv", index=False)

In [15]:
for index, row in Update_Conv.iterrows():
    Id = row['ConversionId'] 
    if Id in Conversions['ConversionId'].values:
        Conversions.drop(Conversions[Conversions['ConversionId'] == Id].index, inplace=True)
    else:
        print(f"Warning: 'ConversionId' {Id} not found in Conversions DataFrame. Skipping drop operation.")

Warning: 'ConversionId' I-4140 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-4134 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-4190 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-1660 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-2121 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-16224 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-1588 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-16638 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-14948 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-3498 not found in Conversions DataFrame. Skipping drop operation.
Warning: 'ConversionId' I-4207 not found in Conversions DataFrame. Skipping drop operation.

In [16]:
frames = [Conversions, Update_Conv]
Conversions = pd.concat(frames).reset_index(drop=True, inplace=False).drop_duplicates()

In [17]:
Conversions

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-4226,0.002205,50.00,LBS,22679.500,g
1,I-1971,0.014925,0.25,ea,16.750,g
2,I-15803,0.004000,1.00,can,250.000,ml
3,I-5505,0.005051,0.25,HEAD,49.500,g
4,I-11706,0.008547,1.00,ea,117.000,g
...,...,...,...,...,...,...
222,I-10834,0.001102,1.00,ea,907.185,g
223,I-4253,0.000352,6.00,can,17040.000,g
224,I-12362,0.010000,0.50,ea,50.000,g
225,I-12363,0.010000,0.50,ea,50.000,g
226,I-12364,0.010000,1.00,ea,100.000,g

In [18]:
# Convert the DataFrame: Conversions into a csv file called Conversions_Added.csv
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Conversions_Added.csv")
Conversions.to_csv(path, index = False, header = True)

***
## Converter

### Create Unit Converter

In [19]:
# Import standard unit conversion information and construct a dataframe
Std_Unit = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "standard_conversions.csv"))
Std_Unit.head()

   Multiplier  ConvertFromQty ConvertFromUom  ConvertToQty ConvertToUom
0     4.92890               1            tsp       4.92890           ml
1    14.78700               1           Tbsp      14.78700           ml
2   946.35000               1             qt     946.35000           ml
3   473.17625               1             pt     473.17625           ml
4    28.34950               1             oz      28.34950            g

In [20]:
# Seperate uoms that converted to 'ml' or 'g'
# Below we create 2 lists. 
# list_unit contains list of unit of measurements that are being converted to milliliters 
# solid_unit contains a list of unit of measurements that are being converted to grams
# tolist() converts a Pandas Series or an array to a python list. 

liquid_unit = Std_Unit.loc[Std_Unit['ConvertToUom'] == 'ml', 'ConvertFromUom'].tolist()
solid_unit = Std_Unit.loc[Std_Unit['ConvertToUom'] == 'g', 'ConvertFromUom'].tolist()

In [21]:
# Construct a standard unit converter
def std_converter(qty, uom):
    if uom in Std_Unit['ConvertFromUom'].tolist():
        multiplier = Std_Unit.loc[Std_Unit['ConvertFromUom'] == uom, 'Multiplier']
        Qty = float(qty)*float(multiplier)
        Uom = Std_Unit.loc[Std_Unit['ConvertFromUom'] == uom, 'ConvertToUom'].values[0]
    else:
        Qty = qty
        Uom = uom
    return (Qty, Uom)

In [22]:
# Construct a unit converter for specific ingredients

# After this line below, spc_cov contains only the non-empty values from the 'ConversionId' column of the Conversions DataFrame.
spc_cov = list(filter(None, Conversions['ConversionId'].tolist()))


# Comments for spc_converter:
# The function checks if ingredient is in the liquid_unit or solid_unit lists. If so, it calls std_converter(qty, uom) to 
# convert the quantity and UOM to a standardized unit.

# If uom is not in liquid_unit or solid_unit it checks if ingre is in spc_cov, if it is and the ConvertToUom is equal to grams 
# then the function applies the factor to the qty argument to convert it to the standardized unit, and returns the result as
# a tuple containing the converted quantity and uom. If no conversion found, then it calls std_converter(qty, uom)

# If uom not in liquid_unit or solid_unit and if ingre is not in spc_cov then the function calls std_converter(qty, uom)

def spc_converter(ingre, qty, uom):
    if uom in liquid_unit + solid_unit:
        return std_converter(qty, uom)
    elif ingre in spc_cov:
        conversion = Conversions.loc[(Conversions['ConversionId'] == ingre) & (Conversions['ConvertFromUom'] == uom)
                                    & (Conversions['ConvertToUom'].isin(["ml", "g"]))]
        multiplier = conversion['Multiplier']
        print(multiplier)
        if multiplier.empty:
            return std_converter(qty, uom)
        else: 
            Qty = float(qty)/float(multiplier)
            Uom = conversion['ConvertToUom'].values[0]
            return (Qty, Uom)
    else:
        return std_converter(qty, uom)

In [23]:
# spc_cov2 is the same as spc_cov but without null values labelled as "nan" in the list
import math
spc_cov2 = [item for item in spc_cov if not(pd.isnull(item)) == True]
spc_cov2

['I-4226',
 'I-1971',
 'I-15803',
 'I-5505',
 'I-11706',
 'I-13308',
 'I-15514',
 'I-4082',
 'I-1789',
 'I-2919',
 'I-13956',
 'I-1752',
 'I-5899',
 'I-4014',
 'I-7647',
 'I-10942',
 'I-13719',
 'I-9665',
 'I-2087',
 'I-13414',
 'I-17486',
 'I-16570',
 'I-1541',
 'I-12354',
 'I-17316',
 'I-1549',
 'I-13577',
 'I-2992',
 'I-14905',
 'I-1963',
 'I-5265',
 'I-5126',
 'I-14948',
 'I-2121',
 'I-3498',
 'I-14218',
 'I-16223',
 'I-3337',
 'I-8151',
 'I-15477',
 'I-3354',
 'I-2133',
 'I-16638',
 'I-9017',
 'I-13813',
 'I-14126',
 'I-14127',
 'I-3700',
 'I-13598',
 'I-1695',
 'I-12060',
 'I-15051',
 'I-16221',
 'I-16794',
 'I-16784',
 'I-16785',
 'I-4697',
 'I-16789',
 'I-15673',
 'I-4041',
 'I-4098',
 'I-4130',
 'I-7789',
 'I-9599',
 'I-9600',
 'I-9601',
 'I-16242',
 'I-14978',
 'I-15486',
 'I-7804',
 'I-4022',
 'I-14442',
 'I-16637',
 'I-13816',
 'I-2071',
 'I-17990',
 'I-17991',
 'I-1626',
 'I-14517',
 'I-13109',
 'I-12921',
 'I-15369',
 'I-18257',
 'I-8091',
 'I-5103',
 'I-7335',
 'I-2319',
 'I-14841',
 'I-12306',
 'I-14638',
 'I-1553',
 'I-15495',
 'I-1835',
 'I-15475',
 'I-1787',
 'I-15409',
 'I-1833',
 'I-13385',
 'I-15066',
 'I-14146',
 'I-9034',
 'I-11631',
 'I-14339',
 'I-14340',
 'I-14341',
 'I-14342',
 'I-14586',
 'I-2676',
 'I-4296',
 'I-8250',
 'I-13957',
 'I-14390',
 'I-8298',
 'I-3181',
 'I-16224',
 'I-12034',
 'I-1471',
 'I-14208',
 'I-12353',
 'I-16226',
 'I-8990',
 'I-15017',
 'I-17134',
 'I-2032',
 'I-11233',
 'I-15596',
 'I-15597',
 'I-14400',
 'I-2375',
 'I-12339',
 'I-2586',
 'I-9186',
 'I-15425',
 'I-2432',
 'I-5221',
 'I-4134',
 'I-5222',
 'I-5224',
 'I-4125',
 'I-4207',
 'I-4172',
 'I-4118',
 'I-41390',
 'I-4140',
 'I-2066',
 'I-11093',
 'I-4153',
 'I-4161',
 'I-4162',
 'I-4188',
 'I-4190',
 'I-4193',
 'I-4201',
 'I-5075',
 'I-1660',
 'I-1588',
 'I-4211',
 'I-6203',
 'I-4128',
 'I-4234',
 'I-4236',
 'I-4101',
 'I-4114',
 'I-4126',
 'I-4132',
 'I-4135',
 'I-4137',
 'I-4139',
 'I-4140',
 'I-4142',
 'I-4143',
 'I-14422',
 'I-4195',
 'I-4134',
 'I-4158',
 'I-4170',
 'I-4190',
 'I-4230',
 'I-4237',
 'I-4238',
 'I-4239',
 'I-4240',
 'I-4241',
 'I-4109',
 'I-4122',
 'I-3805',
 'I-3806',
 'I-3807',
 'I-3810',
 'I-3815',
 'I-3816',
 'I-3817',
 'I-3820',
 'I-4107',
 'I-4133',
 'I-4136',
 'I-4141',
 'I-4151',
 'I-4163',
 'I-4166',
 'I-4181',
 'I-2121',
 'I-16224',
 'I-4129',
 'I-4138',
 'I-4144',
 'I-2498',
 'I-2102',
 'I-1651',
 'I-4173',
 'I-4204',
 'I-15736',
 'I-4127',
 'I-16638',
 'I-14948',
 'I-3498',
 'I-4207',
 'I-1635',
 'I-4212',
 'I-1637',
 'I-10834',
 'I-4253',
 'I-12362',
 'I-12363',
 'I-12364']

***
## Items with Non-standard Units

In [24]:
Ingredients

   IngredientId    Qty      Uom   Recipe
0       P-10125    1.0       ea  R-10977
1        P-7216    1.0       ea  R-10977
2        I-4212  250.0        g  R-10977
3        I-2119  150.0       ml  R-10977
4        I-4163   10.0      LBS  P-10125
5        I-1635    1.0       ea  P-10125
6        I-4184  250.0       ml  P-10125
7        I-2929  500.0        g  P-10125
8        P-7216   10.0       ea  P-10125
9        I-4212    2.0      bag  P-10125
10       I-4127    1.0       ea   P-7216
11       I-6865    3.0  oz (wt)   P-7216
12       I-1874    1.0  oz (wt)   P-7216
13       I-2119   30.0       ml   P-7216
14       I-1958  400.0       ml   P-7216
15       I-2366   50.0        g   P-7216
16       I-2436   50.0       ml   P-7216
17       I-2323    1.0      tsp   P-7216

In [25]:
Items

,ItemId,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4212,Fries Wedge Savory Supercrisp,2.0,bag,22.0,ea,Y
1,I-2119,PFO OIL CANOLA JIB ANTI FOAM,250.0,ml,1.2,Kg,Y
2,I-4163,HALAL- Chk Leg B/less SkinON,10.0,LBS,20.0,PORT,Y
3,I-1635,BUTTERMILK 3.25%,2300.0,ml,36.0,ea,Y
4,I-4184,SAUCE RED HOT,20.0,ml,1.0,L,Y
5,I-2929,Corn Meal,1250.0,g,36.0,ea,Y
6,I-4127,BANANA 5lb,4.0,ea,10.0,ea,Y
7,I-6865,Onion White Peeled,160.0,g,8.0,ea,Y
8,I-1874,GARLIC WHOLE PEELED,30.0,g,1000.0,ml,Y
9,I-1958,KETCHUP VOL PAK,500.0,ml,1.0,L,Y
10,I-2366,SUGAR GOLDEN YEL,1300.0,g,1.5,Kg,Y
11,I-2436,VINEGAR APPLE CIDER PURE,20.0,ml,8.0,ea,Y
12,I-2323,SPICE CAYENNE SHAKER,5.0,oz (fl),350.0,g,Y

In [26]:
# Filter out the items whose unit information is unknown 
# We find the column names
col_names = list(Ingredients.columns.values)

# Create a Items_Nonstd list
Items_Nonstd = []

# If the unit of measurement is not grams or ml and ingredient id starts with I and the ingredient is not in ConversionId column of Conversions 
# then we add it to Items_Nonstd list
for index, row in Ingredients.iterrows():
    Ingre = Ingredients.loc[index,'IngredientId']
    Uom = Ingredients.loc[index,'Uom']
    if Uom not in ['g', 'ml'] and Uom not in liquid_unit + solid_unit and Ingre.startswith('I'):
        Dict = {}
        Dict.update(dict(row))
        Items_Nonstd.append(Dict)

# Create a DataFrame from Items_Nonstd list
Items_Nonstd = pd.DataFrame(Items_Nonstd, columns = col_names)
# Remove duplicate ingredients of the same properties so that Items_Nonstd has only unique rows. 
Items_Nonstd.drop_duplicates(subset=['IngredientId'], inplace=True,)
Items_Nonstd

  IngredientId   Qty  Uom   Recipe
0       I-4163  10.0  LBS  P-10125
1       I-1635   1.0   ea  P-10125
2       I-4212   2.0  bag  P-10125
3       I-4127   1.0   ea   P-7216

In [27]:
# Assigning a Description column to the Items_Nonstd    
for index, row in Items_Nonstd.iterrows():
    idx = row['IngredientId']
    filtered_items = Items.loc[Items['ItemId'] == idx, 'Description']
    if not filtered_items.empty:
        descrp = filtered_items.values[0]
        Items_Nonstd.loc[index, 'Description'] = descrp
    else:
        # Handle the case when there is no matching item for the given 'IngredientId'
        Items_Nonstd.loc[index, 'Description'] = 'Not Found'
        pass

In [28]:
Items_Nonstd.head()

  IngredientId   Qty  Uom   Recipe                    Description
0       I-4163  10.0  LBS  P-10125   HALAL- Chk Leg B/less SkinON
1       I-1635   1.0   ea  P-10125               BUTTERMILK 3.25%
2       I-4212   2.0  bag  P-10125  Fries Wedge Savory Supercrisp
3       I-4127   1.0   ea   P-7216                     BANANA 5lb

In [29]:
# Convert the Items_Nonstd DataFrame to a csv file
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Items_Nonstd.csv")
Items_Nonstd.to_csv(path, index = False, header = True)

***
## Clean Preps Units

In [30]:
Preps

    PrepId                Description  PakQty PakUOM InventoryGroup
0  P-10125  Club - Buttermilk Chicken    22.0     ea              Y
1   P-7216      Club - Banana Ketchup    10.0   PORT              Y

In [31]:
preps_updateuom = pd.read_csv("data/cleaning/update/AMS_data/Preps_UpdateUom.csv")

In [32]:
# Creates 2 new columns called StdQty and StdUom in the Preps DataFrame. These columns contain NaN values
# Preparing to fill in these columns with standardized quantities and units of measurement 
Preps['StdQty'] = np.nan
Preps['StdUom'] = np.nan

In [33]:
# # Convert uom into 'g' or 'ml' for each prep using the unit converter

# # Retrieve the PrepId, PakQty, and PakUOM from the current row
# # Pass these values to spc_converter, then we update the StdQty and StdUom columns of the current row with the converted values.
# for index in Preps.index:
#     PrepId = Preps.loc[index,'PrepId']
#     Qty = Preps.loc[index,'PakQty']
#     Uom = Preps.loc[index,'PakUOM']
#     Preps.loc[index,'StdQty'] = spc_converter(PrepId, Qty, Uom)[0]
#     Preps.loc[index,'StdUom'] = spc_converter(PrepId, Qty, Uom)[1]

In [34]:
Preps

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-10125,Club - Buttermilk Chicken,22.0,ea,Y,NaN,NaN
1,P-7216,Club - Banana Ketchup,10.0,PORT,Y,NaN,NaN

In [35]:
Preps.shape

(2, 7)

In [36]:
# Function to apply the conversion logic
def convert_units(row):
    if row['PakUOM'].lower() in ['g', 'grams']:
        return row['PakQty'], 'g'
    elif row['PakUOM'].lower() in ['kg']:
        return row['PakQty'] * 1000, 'g'
    elif row['PakUOM'].lower() in ['ml']:
        return row['PakQty'], 'ml'
    elif row['PakUOM'].lower() in ['l']:
        return row['PakQty'] * 1000, 'ml'
    elif row['PakUOM'].lower() in ['lbs']:
        return row['PakQty'] * 453.59, 'g'
    else:
        return np.nan, np.nan

# Apply the function to each row
Preps['StdQty'], Preps['StdUom'] = zip(*Preps.apply(convert_units, axis=1))

In [37]:
Preps_Cleaned = Preps[~Preps["StdQty"].isna()]
Preps_Cleaned.reset_index(drop=True, inplace=True)
Preps_Cleaned

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [38]:
# Save cleaned preps list to file
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Preps_Unit_Cleaned.csv")
Preps_Cleaned.to_csv(path, index = False, header = True)

### Get Preps with Nonstandard Unit

In [39]:
col_names = list(Preps.columns.values)
Preps_Nonstd = []

for index, row in Preps.iterrows():
    StdUom = Preps.loc[index,'StdUom']
    if StdUom not in ['g', 'ml']:
        Dict = {}
        Dict.update(dict(row))
        Preps_Nonstd.append(Dict)

Preps_Nonstd = pd.DataFrame(Preps_Nonstd, columns = col_names)

In [40]:
Preps_Nonstd

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-10125,Club - Buttermilk Chicken,22.0,ea,Y,NaN,NaN
1,P-7216,Club - Banana Ketchup,10.0,PORT,Y,NaN,NaN

In [41]:
# for _,row in Preps_Nonstd.iterrows():
#     try:
#         prepID = row["PrepId"]
#         recipe = Ingredients.loc[Ingredients["Recipe"] == prepID]
#         final_weight = 0
#         if not recipe.empty:
#             for _,row  in recipe.iterrows():
#                 qty = row["Qty"]
#                 uom = row["Uom"]
#                 itemID = row["IngredientId"]
#                 converted = spc_converter(itemID, qty, uom)
#                 if converted[1] == "g" or converted[1] == "ml":
#                     final_weight += converted[0]
#                 else:
#                     if row["IngredientId"].startswith("P"):
#                         new_weight = preps_updateuom.loc[preps_updateuom["PrepId"] == row["IngredientId"]]["StdQty"]
#                         if not new_weight.empty:
#                             final_weight += new_weight
#                         else:
#                             raise Exception(f'Item with ID {row["IngredientId"]} not in standard units,it is in the unit {converted[1]}')         
#                     elif row["IngredientId"].startswith("I"):
#                         conversion = Conversions.loc[Conversions["ConversionId"] == row["IngredientId"]]
#                         print(conversion)
#                         if not conversion.empty and conversion["ConvertFromUom"] == row["Uom"]:
#                             final_weight += conversion["Multiplier"] * qty
#                         else:
#                             error_string = f'Item with ID {row["IngredientId"]} not in standard units,it is in the unit {converted[1]}'
#                             if conversion["ConvertFromUom"] != row["Uom"]:
#                                 error_string += f'Item is in UOM {conversion["ConvertFromUom"]}'
#                             else:
#                                 error_string = error_string
#                             raise Exception(error_string)
#         else:
#             raise Exception("PrepId not found in Ingredients")
#         Preps.loc[Preps["PrepId"] == prepID, "StdQty"] = final_weight
#     except Exception as e:
#         print(e)

# Using vectorized operations to avoid iterrows() for better performance
preps_updateuom_dict = preps_updateuom.set_index("PrepId")["StdQty"].to_dict()
conversions_dict = Conversions.set_index("ConversionId")[["ConvertFromUom", "Multiplier"]].to_dict()

def calculate_final_weight(prepID):
    try:
        recipe = Ingredients[Ingredients["Recipe"] == prepID]
        if recipe.empty:
            raise ValueError("PrepId not found in Ingredients")

        final_weight = 0
        for _, recipe_row in recipe.iterrows():
            qty = recipe_row["Qty"]
            uom = recipe_row["Uom"]
            itemID = recipe_row["IngredientId"]

            print(f"Processing ItemID: {itemID}, Qty: {qty}, UOM: {uom}")

            converted = spc_converter(itemID, qty, uom)
            if converted[1] in ["g", "ml"]:
                final_weight += converted[0]
            else:
                if itemID.startswith("P"):
                    # Handle prep item conversion using preps_updateuom
                    new_weight = preps_updateuom_dict.get(itemID)
                    if new_weight is not None:
                        final_weight += new_weight
                    else:
                        raise ValueError(f'Item with ID {itemID} not in standard units, it is in the unit {converted[1]}')
                elif itemID.startswith("I"):
                    # Handle ingredient conversion using Conversions
                    conversion_uom = conversions_dict["ConvertFromUom"].get(itemID)
                    conversion_multiplier = conversions_dict["Multiplier"].get(itemID)

                    if conversion_uom and conversion_uom == recipe_row["Uom"]:
                        final_weight += conversion_multiplier * qty
                    else:
                        error_string = f'Item with ID {itemID} not in standard units, it is in the unit {converted[1]}'
                        if conversion_uom and conversion_uom != recipe_row["Uom"]:
                            error_string += f'. Item is in UOM {conversion_uom}'
                        raise ValueError(error_string)

        return final_weight
    except Exception as e:
        # Handle or log the error (you can log the error message if needed)
        return str(e)

# Apply the function to Preps_Nonstd and update the Preps dataframe
Preps_Nonstd["StdQty"] = Preps_Nonstd["PrepId"].apply(calculate_final_weight)
Preps_Nonstd["StdUom"] = "g"
# Update the Preps dataframe with the calculated weights
for index, row in Preps_Nonstd.iterrows():
    PrepId = row['PrepId']
    StdQty = row['StdQty']
    Preps.loc[Preps['PrepId'] == PrepId, 'StdQty'] = StdQty
    Preps.loc[Preps['PrepId'] == PrepId, 'StdUom'] = 'g'

Processing ItemID: I-4163, Qty: 10.0, UOM: LBS
198    0.002205
Name: Multiplier, dtype: float64
Processing ItemID: I-1635, Qty: 1.0, UOM: ea
219    0.004082
Name: Multiplier, dtype: float64
Processing ItemID: I-4184, Qty: 250.0, UOM: ml
Processing ItemID: I-2929, Qty: 500.0, UOM: g
Processing ItemID: P-7216, Qty: 10.0, UOM: ea
Processing ItemID: I-4212, Qty: 2.0, UOM: bag
220    0.01
Name: Multiplier, dtype: float64
Processing ItemID: I-4127, Qty: 1.0, UOM: ea
214    0.008333
Name: Multiplier, dtype: float64
Processing ItemID: I-6865, Qty: 3.0, UOM: oz (wt)
Processing ItemID: I-1874, Qty: 1.0, UOM: oz (wt)
Processing ItemID: I-2119, Qty: 30.0, UOM: ml
Processing ItemID: I-1958, Qty: 400.0, UOM: ml
Processing ItemID: I-2366, Qty: 50.0, UOM: g
Processing ItemID: I-2436, Qty: 50.0, UOM: ml
Processing ItemID: I-2323, Qty: 1.0, UOM: tsp

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_75223/3329881030.py:28: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Qty = float(qty)/float(multiplier)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_75223/3899604546.py:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  Qty = float(qty)*float(multiplier)
/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_75223/1138546375.py:94: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'g' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  Preps.loc[Preps['PrepId'] == PrepId, 'StdUom'] = 'g'

In [42]:
Preps_Nonstd

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-10125,Club - Buttermilk Chicken,22.0,ea,Y,6499.2489,g
1,P-7216,Club - Banana Ketchup,10.0,PORT,Y,768.3289,g

In [43]:
Preps

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-10125,Club - Buttermilk Chicken,22.0,ea,Y,6499.2489,g
1,P-7216,Club - Banana Ketchup,10.0,PORT,Y,768.3289,g

In [44]:
# # Filter out preps with nonstandard uom but have information already

# Manual_PrepU = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "AMS_data", "Preps_UpdateUom.csv"))

# col_names = list(Preps_Nonstd.columns.values)
# Preps_Nonstd_na = []

# # for index, row in Preps_Nonstd.iterrows():
# #     PrepId = Preps_Nonstd.loc[index,'PrepId']
# #     if PrepId not in Manual_PrepU['PrepId'].values or Preps_Nonstd.loc[index,"StdUom"] != "g":
# #         Dict = {}
# #         Dict.update(dict(row))
# #         Preps_Nonstd_na.append(Dict)

# for idx, row in Preps_Nonstd.iterrows():
#     PrepID = Preps_Nonstd.loc[idx, 'PrepId']
#     Manual_PakQty = Manual_PrepU.loc[Manual_PrepU['PrepId'] == PrepID, 'PakQty']
#     Manual_PakUOM = Manual_PrepU.loc[Manual_PrepU['PrepId'] == PrepID, 'PakUOM']
#     Nonstd_PakQty = Preps_Nonstd.loc[idx, 'PakQty']
#     Nonstd_PakUOM = Preps_Nonstd.loc[idx, 'PakUOM']
#     if ((Manual_PakQty.empty or Manual_PakUOM.empty) or 
#         (Manual_PakQty.values[0] != Nonstd_PakQty or Manual_PakUOM.values[0] != Nonstd_PakUOM) or 
#         (Preps_Nonstd.loc[idx, "StdUom"] != "g")):
#         Dict = {}
#         Dict.update(dict(row))
#         Preps_Nonstd_na.append(Dict)

# Preps_Nonstd = pd.DataFrame(Preps_Nonstd_na, columns = col_names)
# Preps_Nonstd

In [45]:
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Preps_NonstdUom.csv")
Preps_Nonstd.to_csv(path, index = False, header = True)

In [46]:
# NEED TO CONTINUE FROM HERE, FINISH THE UNIT UPDATES
update_prep = pd.read_csv("data/cleaning/update/AMS_data/Preps_UpdateUom.csv")
update_prep #Manual? yes

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-14356,[PREP KAPPA MAKI,6.0,PORT,N,1511.8200,g
1,P-14560,2023 Chicken Caesar wrap Prep,1.0,ea,Y,433.5900,g
2,P-9003,2022 Gallery Burger prep,1.0,ea,N,501.8200,g
3,P-17358,2023 Poutine Prep,1.0,ea,N,705.8000,g
4,P-15006,2023 Power Punch Salad Prep,1.0,ea,N,416.7300,g
...,...,...,...,...,...,...,...
112,P-2584,Lg chicken plate prep S2025,1.0,ea,Y,1036.9000,g
113,P-6881,Lime sourcream 2024,28.8,ea,Y,1018.0000,g
114,P-3045,Poached Shrimp S 2025,1.0,ea,Y,2065.0000,g
115,P-7201,Prep Battered Basa S 2025,10.0,ea,Y,5644.0000,g
116,P-7216,Club - Banana Ketchup,10.0,PORT,Y,768.3289,g

In [47]:
# Assuming update_prep and Preps_Nonstd are DataFrames and 'PrepId' is the column of interest
update = set(update_prep["PrepId"])
preps = set(Preps_Nonstd["PrepId"])

# Find the difference between the sets
difference = preps - update

# If you want to print or use the difference
print(difference)

{'P-10125'}

***

## New Items

In [48]:
# Load current Items List with assigned Emission Factors Category ID
Items_Assigned = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "AMS_data", "Items_List_Assigned.csv"))
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,NaN
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,NaN
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,NaN
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,NaN
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,NaN

In [49]:
Items_Assigned.shape

(582, 9)

In [50]:
Items_Assigned["InventoryGroup"].unique()

array(['N', 'Y'], dtype=object)

In [51]:
Items_Assigned["CategoryID"].unique()

array([35, 55, 31, 36, 58, 24, 16, 20,  3, 40,  8, 38, 48, 54, 44, 18, 32,
       56, 61, 39, 43, 37,  5, 26, 25,  9,  4, 22,  6, 49, 12, 50, 41, 17,
       57, 11, 34,  1, 45, 42, 59, 46, 10, 51, 53, 21, 28,  7, 13, 30, 14,
       19, 27])

In [52]:
Items_Assigned[Items_Assigned["CategoryID"] == 55]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
1,I-8228,55,Grey Goose 1.14L,1.0,fl oz,1.0,fl oz,N,NaN
33,I-2640,55,Water - Tap,250.0,ml,2.5,ml,N,NaN
92,I-13817,55,FRENCH AUS JUS,490.0,g,5.0,g,N,NaN
102,I-15592,55,JUICE ORANGE CONC 6+1,500.0,ml,13.0,ml,N,NaN
121,I-3036,55,MIRIN 5.28GL,720.0,ml,2100.0,fl oz,N,NaN
171,I-2103,55,PEACH SLCD IN PEAR JUICE,300.0,ml,300.0,ml,N,NaN
172,I-6204,55,Juice - Lime Fresh Squeezed,30.0,g,300.0,oz,N,NaN
212,I-17946,55,JUICE orange 100% tetra,1.0,L,6.0,ml,Y,NaN
228,I-6203,55,Juice - Lemon Fresh Squeezed,50.0,g,1.2,oz,Y,NaN
270,I-17129,55,Boiling Water,3000.0,g,2000.0,g,N,NaN
274,I-5981,55,Aperol Aperitivo,6.0,L,18.0,fl oz,Y,NaN
284,I-6182,55,BIB - Coca-Cola 20L,1.0,L,6.0,fl oz,N,NaN
285,I-6189,55,BIB - Coke Zero 10L,1.0,L,6.0,fl oz,N,NaN
286,I-6188,55,BIB -Canada Dry Ginger Ale 10L,1.0,L,6.0,fl oz,N,NaN
287,I-6185,55,BIB - Nestea 20L,1.0,L,6.0,fl oz,N,NaN
288,I-12929,55,BIB- Sprite 10L,1.0,L,6.0,fl oz,N,NaN
289,I-6224,55,BIB - Tonic Water 12L,1.0,L,6.0,fl oz,N,NaN
319,I-7335,55,Tea Assam Brkfst Two Leaves,3.0,ea,4.0,ea,N,NaN
373,I-1081,55,GRAND MARNIER,375.0,ml,13.0,fl oz,Y,NaN
388,I-9117,55,Sawmill Creek - White 16L,1.8,L,2.0,fl oz,N,NaN
390,I-7801,55,Sawmill Creek - Red 16L,7.5,L,400.0,fl oz,N,NaN
392,I-1471,55,Kronenbourg 1664 Blanc,1.0,bottle,0.6,bottle,N,NaN
441,I-1052,55,BACARDI LIGHT RUM,200.0,ml,18.5,fl oz,Y,NaN
442,I-1945,55,JUICE PINEAPPLE CAN,350.0,ml,18.5,ml,Y,NaN
444,I-5960,55,St Remy Brandy,150.0,ml,18.5,fl oz,Y,NaN
447,I-1093,55,MALIBU liquor,375.0,ml,18.0,fl oz,Y,NaN
448,I-1109,55,Meagher's Triple Sec,375.0,ml,18.0,fl oz,Y,NaN
450,I-16601,55,Sawmill Creek -Rose 4L,8.0,L,18.0,fl oz,Y,NaN
490,I-4171,55,Tap Water,10.0,g,1.0,ea,Y,water & beverages

### Get the List of New Items

In [53]:
# Filter new items by itemID that are not in the database and output them in a dataframe
col_names = list(Items.columns.values)
New_Items_List = []

for index, row in Items.iterrows():
    ItemId = Items.loc[index,'ItemId']
    descrp = Items.loc[index,'Description']
    if ItemId not in Items_Assigned['ItemId'].values:
        Dict = {}
        Dict.update(dict(row))
        New_Items_List.append(Dict)
    else:
        print("ItemID: ", ItemId, descrp, " already exists in the database")

New_Items = pd.DataFrame(New_Items_List, columns = col_names)

ItemID:  I-4212 Fries Wedge Savory Supercrisp  already exists in the database
ItemID:  I-2119 PFO OIL CANOLA JIB  ANTI FOAM  already exists in the database
ItemID:  I-4163 HALAL- Chk Leg B/less SkinON  already exists in the database
ItemID:  I-1635 BUTTERMILK 3.25%  already exists in the database
ItemID:  I-4184 SAUCE RED HOT  already exists in the database
ItemID:  I-2929 Corn Meal  already exists in the database
ItemID:  I-4127 BANANA 5lb  already exists in the database
ItemID:  I-6865 Onion White Peeled  already exists in the database
ItemID:  I-1874 GARLIC WHOLE PEELED  already exists in the database
ItemID:  I-1958 KETCHUP VOL PAK  already exists in the database
ItemID:  I-2366 SUGAR GOLDEN YEL  already exists in the database
ItemID:  I-2436 VINEGAR APPLE CIDER PURE  already exists in the database
ItemID:  I-2323 SPICE CAYENNE SHAKER   already exists in the database

In [54]:
New_Items.insert(1, "CategoryID", '')
New_Items

Empty DataFrame
Columns: [ItemId, CategoryID, Description, CaseQty, CaseUOM, PakQty, PakUOM, InventoryGroup]
Index: []

In [55]:
New_Items.shape

(0, 8)

In [56]:
# Store the list of new items into .csv file
# If New_Items is not empty then we convert it to a csv file. 
if not New_Items.empty:
    path = os.path.join(os.getcwd(), "data", "mapping", "AMS_data", "new items", str(datetime.date(datetime.now()))+"_New_Items.csv")
    New_Items.to_csv(path, index = False, header = True)

***
## Data Summary

In [57]:
datasum = pd.DataFrame([New_Items.shape, Preps_Nonstd.shape, Items_Nonstd.shape],
                       columns = ['count', 'columns'], 
                       index = ['New_Items', 'Preps_Nonstd', 'Items_Nonstd'])
datasum

              count  columns
New_Items         0        8
Preps_Nonstd      2        7
Items_Nonstd      4        5

In [58]:
print(New_Items.columns)

Index(['ItemId', 'CategoryID', 'Description', 'CaseQty', 'CaseUOM', 'PakQty',
       'PakUOM', 'InventoryGroup'],
      dtype='object')