# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

***

## Part III: Update Information and Mapping

## Set up and Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  os
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse
from datetime import datetime

In [2]:
# RUN ONLY ONCE
# os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

***
## Import Preprocessed Datasets

In [3]:
# Creates a DataFrame from reading a csv file 
Preps = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Preps_Unit_Cleaned.csv"))
Preps.head()

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [4]:
# Creates a DataFrame from reading a csv file 
ghge_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "ghge_factors.csv"))
ghge_factors.head()

,Category ID,Food Category,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,1,beef & buffalo meat,85.5822
1,2,lamb/mutton & goat meat,39.7200
2,3,pork (pig meat),12.3100
3,4,"poultry (chicken, turkey)",9.8700
4,5,butter,16.1300

In [5]:
# Creates a DataFrame from reading a csv file 
nitro_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "nitrogen_factors.csv"))
nitro_factors.head()

eutro_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "eutrophying_factors.csv"))
eutro_factors.head()

,Category ID,Food Category,Eutrophying Emissions (g PO43-eq / kg food)
0,1,beef & buffalo meat,314.8248
1,2,lamb/mutton & goat meat,97.1300
2,3,pork (pig meat),76.3800
3,4,"poultry (chicken, turkey)",48.7000
4,5,butter,54.5300

In [6]:
# Creates a DataFrame from reading a csv file 
water_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "water_factors.csv"))
water_factors.head()

,Category ID,Food Category,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,1,beef & buffalo meat,1716.451,52597.767
1,2,lamb/mutton & goat meat,1802.800,141925.000
2,3,pork (pig meat),1795.800,66867.400
3,4,"poultry (chicken, turkey)",660.000,14177.900
4,5,butter,3216.720,101316.490

In [7]:
# Creates a DataFrame from reading a csv file 
land_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "land_factors.csv"))
land_factors.rename(columns={'km^2 land use/kg product': 'Land Use (m^2)'}, inplace=True)
land_factors['Land Use (m^2)'] *= 1000
land_factors.head()

   Category ID              Food Category  Land Use (m^2)
0            1        beef & buffalo meat        0.266786
1            2    lamb/mutton & goat meat        0.369810
2            3            pork (pig meat)        0.017360
3            4  poultry (chicken, turkey)        0.012220
4            5                     butter        0.045830

In [8]:
# Load current Items List with assigned Emission Factors Category ID
Items_Assigned = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "AMS_data", "Items_List_Assigned.csv"))
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,NaN
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,NaN
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,NaN
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,NaN
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,NaN

In [9]:
# new_items = pd.read_csv("data/mapping/new items added/New_Items_Added_11.csv")
# new_items = pd.read_csv("data/mapping/new items added/New_Items_2023/New_Items_Added_2023_08_01.csv")
# CHECK FOR CHANGES REQUIRES

# # COMMENTED OUT LINES BELOW, commented it out this time because no new items were added

new_items = pd.read_csv("data/mapping/AMS_data/new items/2025-07-15_New_Items.csv")
new_items.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4121,22,Corn Starch 50lb,20.0,g,0.5,L,Y
1,I-4150,35,Juice Orange break. 100 %,400.0,ml,755.0,ml,Y
2,I-4151,35,ORANGES 5lb,1.0,ea,755.0,ml,Y
3,I-4163,20,Tofu MED Firm Sunrise,0.5,454G,1.0,ea,Y
4,I-4167,58,ITEM DRES ASIAN SESAME,2.0,oz (fl),1.0,ea,Y

In [10]:
item_nonstd = pd.read_csv("data/cleaning/AMS_data/Items_Nonstd.csv")
item_nonstd

Empty DataFrame
Columns: [IngredientId, Qty, Uom, Recipe, Description]
Index: []

In [11]:
preps_nonstd = pd.read_csv("data/cleaning/AMS_data/Preps_NonstdUom.csv")
preps_nonstd

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [12]:
conv_updatecov = pd.read_csv("data/cleaning/update/AMS_data/Conv_UpdateConv.csv")
conv_updatecov

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-1971,0.014925,0.25,ea,16.750,g
1,I-15803,0.004000,1.00,can,250.000,ml
2,I-5505,0.005051,0.25,HEAD,49.500,g
3,I-11706,0.008547,1.00,ea,117.000,g
4,I-13308,0.024540,1.00,ea,40.750,g
...,...,...,...,...,...,...
221,I-10834,0.001102,1.00,ea,907.185,g
222,I-4253,0.000352,6.00,can,17040.000,g
223,I-12362,0.010000,0.50,ea,50.000,g
224,I-12363,0.010000,0.50,ea,50.000,g
225,I-12364,0.010000,1.00,ea,100.000,g

# Update Conversion_Added.csv

In [13]:
conversions_added = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "AMS_data", "Conversions_Added.csv"))
conversions_added

Empty DataFrame
Columns: [ConversionId, Multiplier, ConvertFromQty, ConvertFromUom, ConvertToQty, ConvertToUom]
Index: []

In [14]:
# Concatenate the DataFrames
combined_df = pd.concat([conv_updatecov, conversions_added], ignore_index=True)
combined_df

/var/folders/tw/grzx75dd27n13qjnqlm37zk80000gn/T/ipykernel_75302/3857027628.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([conv_updatecov, conversions_added], ignore_index=True)

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-1971,0.014925,0.25,ea,16.750,g
1,I-15803,0.004000,1.00,can,250.000,ml
2,I-5505,0.005051,0.25,HEAD,49.500,g
3,I-11706,0.008547,1.00,ea,117.000,g
4,I-13308,0.024540,1.00,ea,40.750,g
...,...,...,...,...,...,...
221,I-10834,0.001102,1.00,ea,907.185,g
222,I-4253,0.000352,6.00,can,17040.000,g
223,I-12362,0.010000,0.50,ea,50.000,g
224,I-12363,0.010000,0.50,ea,50.000,g
225,I-12364,0.010000,1.00,ea,100.000,g

In [15]:
# Add the conv_updatecov file to the masterfile, Conversions_Added
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Conversions_Added.csv")
combined_df.to_csv(path, index = False, header = True)

***
## Import Update Info

In [16]:
# Import list of prep that need convert uom to standard uom manually
Manual_PrepU = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "AMS_data", "Preps_UpdateUom.csv"))
# Here we can see that UOM examples are: each, ea, slice
Manual_PrepU.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-14356,[PREP KAPPA MAKI,6.0,PORT,N,1511.82,g
1,P-14560,2023 Chicken Caesar wrap Prep,1.0,ea,Y,433.59,g
2,P-9003,2022 Gallery Burger prep,1.0,ea,N,501.82,g
3,P-17358,2023 Poutine Prep,1.0,ea,N,705.80,g
4,P-15006,2023 Power Punch Salad Prep,1.0,ea,N,416.73,g

In [17]:
# The row of the DatFrame that contains the PrepId == P-15006
Manual_PrepU.loc[Manual_PrepU["PrepId"] == "P-15006"]

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
4,P-15006,2023 Power Punch Salad Prep,1.0,ea,N,416.73,g

In [18]:
# Select the file path for new items list with category id
# New_Items_Added = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "new items added", "New_Items_Added_10.csv"))
# New_Items_Added.tail(15)

# CHECK FOR CHANGES REQUIRES


# # COMMENTED OUT LINES BELOW, commented it out this time because no new items were added

New_Items_Added = pd.read_csv("data/mapping/new items added/AMS_data/New_items_2025/2025-07-15_New_Items_assigned.csv")
New_Items_Added

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4121,22,Corn Starch 50lb,20.00,g,0.5,L,Y
1,I-4150,35,Juice Orange break. 100 %,400.00,ml,755.0,ml,Y
2,I-4151,35,ORANGES 5lb,1.00,ea,755.0,ml,Y
3,I-4163,20,Tofu MED Firm Sunrise,0.50,454G,1.0,ea,Y
4,I-4167,58,ITEM DRES ASIAN SESAME,2.00,oz (fl),1.0,ea,Y
5,I-4178,51,Rose Cooking Wine 13.2 L,80.00,ml,750.0,g,Y
6,I-4181,40,Lettuce - Romaine 24ct,0.16,ea,170.0,g,Y
7,I-4182,58,ITEM - Nourish Nucc Cham,52.00,ml,170.0,g,Y
8,I-4183,13,SHRIMP White PLDRaw T/on 31-40,63.00,g,1.0,ea,Y
9,I-4185,12,BASA Fillet 10-12 OW,900.00,g,10.0,ea,Y
10,I-5576,26,PUMPKIN SEEDS,4.00,g,4.0,g,Y
11,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y
12,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y
13,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y
14,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y
15,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y

In [19]:
manual_adjust_items = New_Items_Added[New_Items_Added["CategoryID"] == 59]
display(manual_adjust_items)
manual_adjust_items.to_csv("data/mapping/AMS_data/Manual_Adjust_Items.csv", index=False)

Empty DataFrame
Columns: [ItemId, CategoryID, Description, CaseQty, CaseUOM, PakQty, PakUOM, InventoryGroup]
Index: []

In [20]:
# # Import list of items that adjusted GHGe factor manually
Manual_Factor = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping","AMS_data", "Manual_Adjust_Items.csv"))
Manual_Factor['Land Use (m^2)'] = 0
Manual_Factor['Active Total Supply Chain Emissions (kg CO2 / kg food)'] = 0
Manual_Factor['g N lost/kg product'] = 0
Manual_Factor['Freshwater Withdrawals (L/FU)'] = 0
Manual_Factor["Stress-Weighted Water Use (L/FU)"] = 0
Manual_Factor['Eutrophying Emissions (g PO43-eq / kg food)'] = 0
Manual_Factor.head()

Empty DataFrame
Columns: [ItemId, CategoryID, Description, CaseQty, CaseUOM, PakQty, PakUOM, InventoryGroup, Land Use (m^2), Active Total Supply Chain Emissions (kg CO2 / kg food), g N lost/kg product, Freshwater Withdrawals (L/FU), Stress-Weighted Water Use (L/FU), Eutrophying Emissions (g PO43-eq / kg food)]
Index: []

### Update Correct Uom for Preps

In [21]:
# Update prep list with manually adjusted uom
for index, row in Manual_PrepU.iterrows():
    PrepId = Manual_PrepU.loc[index, 'PrepId']
    qty = Manual_PrepU.loc[index, 'StdQty']
    uom = Manual_PrepU.loc[index, 'StdUom']
    Preps.loc[Preps['PrepId'] == PrepId, 'StdQty'] = qty
    Preps.loc[Preps['PrepId'] == PrepId, 'StdUom'] = uom

In [22]:
Preps.drop_duplicates(subset=['PrepId'], inplace=True,)

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [23]:
Preps.head()

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [24]:
Preps.shape

(0, 7)

In [25]:
path = os.path.join(os.getcwd(), "data", "cleaning", "AMS_data", "Preps_List_Cleaned.csv")
Preps.to_csv(path, index = False, header = True)

In [26]:
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,NaN
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,NaN
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,NaN
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,NaN
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,NaN

In [27]:
New_Items_Added.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-4121,22,Corn Starch 50lb,20.0,g,0.5,L,Y
1,I-4150,35,Juice Orange break. 100 %,400.0,ml,755.0,ml,Y
2,I-4151,35,ORANGES 5lb,1.0,ea,755.0,ml,Y
3,I-4163,20,Tofu MED Firm Sunrise,0.5,454G,1.0,ea,Y
4,I-4167,58,ITEM DRES ASIAN SESAME,2.0,oz (fl),1.0,ea,Y

### Import List of New Items with Emission Factors Category ID Assigned

In [28]:
# REMOVED New_Items_Added from frame right now because no new items added. Change this when adding new items (Feb 1 2024)
frames = [Items_Assigned, New_Items_Added]
Items_Assigned_Updated = pd.concat(frames).reset_index(drop=True, inplace=False).drop_duplicates()
# Items_Assigned_Updated.head()

Items_Assigned_Updated.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,NaN
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,NaN
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,NaN
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,NaN
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,NaN

In [29]:
Items_Assigned_Updated[Items_Assigned_Updated["ItemId"] == "I-4152"]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
479,I-4152,40,PEPPERS RED 5LB BAG,400.0,g,2.0,Kg,Y,other fruits

In [30]:
Items_Assigned_Updated[Items_Assigned_Updated["CategoryID"] == 63]

Empty DataFrame
Columns: [ItemId, CategoryID, Description, CaseQty, CaseUOM, PakQty, PakUOM, InventoryGroup, Food Category]
Index: []

In [31]:
Items_Assigned_Updated.shape

(582, 9)

In [32]:
# Double brackets used to specify the column as a dataframe and not a series
# converting the 'CategoryID' column in the Items_Assigned_Updated dataframe to numeric data type using the pd.to_numeric()
# use the apply column to apply the coversion to the entire column
Items_Assigned_Updated[['CategoryID']] = Items_Assigned_Updated[['CategoryID']].apply(pd.to_numeric)

In [33]:
Items_Assigned_Updated
# Items_Assigned_Updated.to_csv("yo.csv")

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,NaN
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,NaN
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,NaN
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,NaN
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,NaN
...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,NaN
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,NaN
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,NaN
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,NaN
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,NaN

In [34]:
path = os.path.join(os.getcwd(), "data", "mapping", "AMS_data", "Items_List_Assigned.csv")
Items_Assigned_Updated.to_csv(path, index = False, header = True)

## Mapping Items to Footprint Factors

In [35]:
# DEFINITION OF MAPPING: assigning certain attributes to data points based on criteria or predefined rules.

# Map GHG footprint factors
# merges two data frames Items_Assigned_Updated and ghge_factors on the columns CategoryID and Category ID, respectively. The 
# resulting data frame is stored in mapping.

# how='left' specifies that a left join is done between Items_Assigned_Updated and ghge_factors.
# left_on='CategoryID' specifies that the join condition for Items_Assigned_Updated should be based on the 'CategoryID' column.
# right_on='Category ID' specifies that the join condition for ghge_factors should be based on the 'Category ID' column.

mapping = pd.merge(Items_Assigned_Updated, ghge_factors.loc[:,['Category ID','Food Category','Active Total Supply Chain Emissions (kg CO2 / kg food)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')
# if row in mapping has CategoryId == NaN then it assigns the value of the column Active Total Supply Chain Emissions (kg CO2 / kg food)
# to zero
for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = 0
# drops the columns Category ID and Food Category
mapping = mapping.drop(columns=['Category ID', 'Food Category_x'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,citrus fruit,0.39
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,water & beverages,0.00
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,other fruits,1.05
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,cabbages and other brassicas (broccoli),0.51
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,sauces & paste,0.00
...,...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,crustaceans (shrimp/prawns),26.87
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,beans and pulses (dried),1.79
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,other vegetables,0.53
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,stimulants & spices misc.,0.00
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,onions and leeks,0.50

In [36]:
# Map nitrogen footprint factors
mapping = pd.merge(mapping, nitro_factors.loc[:,['Category ID','Food Category','g N lost/kg product']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'CategoryID']):
        mapping.loc[index,'g N lost/kg product'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])

# Map eutrophying footprint factors
mapping = pd.merge(mapping, eutro_factors.loc[:,['Category ID','Food Category','Eutrophying Emissions (g PO43-eq / kg food)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Eutrophying Emissions (g PO43-eq / kg food)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food)
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,citrus fruit,0.39,2.70,2.24
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,water & beverages,0.00,0.00,0.00
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,other fruits,1.05,2.70,2.43
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,cabbages and other brassicas (broccoli),0.51,7.90,5.01
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,sauces & paste,0.00,6.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,crustaceans (shrimp/prawns),26.87,70.30,227.22
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,beans and pulses (dried),1.79,5.90,17.08
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,other vegetables,0.53,7.90,2.27
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,stimulants & spices misc.,0.00,6.75,0.00
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,onions and leeks,0.50,7.90,3.24

In [37]:
# Map land footprint factors
mapping = pd.merge(mapping, land_factors.loc[:,['Category ID','Food Category','Land Use (m^2)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'CategoryID']):
        mapping.loc[index,'Land Use (m^2)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2)
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,citrus fruit,0.39,2.70,2.24,0.00086
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,water & beverages,0.00,0.00,0.00,0.00000
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,other fruits,1.05,2.70,2.43,0.00089
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,cabbages and other brassicas (broccoli),0.51,7.90,5.01,0.00055
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,sauces & paste,0.00,6.75,0.00,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,crustaceans (shrimp/prawns),26.87,70.30,227.22,0.00297
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,beans and pulses (dried),1.79,5.90,17.08,0.01557
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,other vegetables,0.53,7.90,2.27,0.00038
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,stimulants & spices misc.,0.00,6.75,0.00,0.00000
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,onions and leeks,0.50,7.90,3.24,0.00039

In [38]:
# Map water footprint factors
# mapping: DataFrame that is used to assign sustainability-related factors (greenhouse gas emissions, nitrogen loss, and 
# water footprint) to food items based on their category and other attributes. 
mapping = pd.merge(mapping, water_factors.loc[:,['Category ID','Food Category','Freshwater Withdrawals (L/FU)', 'Stress-Weighted Water Use (L/FU)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Freshwater Withdrawals (L/FU)'] = 0
        mapping.loc[index,'Stress-Weighted Water Use (L/FU)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping.drop_duplicates(subset=["ItemId"], inplace=True)
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,citrus fruit,0.39,2.70,2.24,0.00086,82.7,4662.7
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,water & beverages,0.00,0.00,0.00,0.00000,1.0,1.0
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,other fruits,1.05,2.70,2.43,0.00089,153.5,9533.1
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,cabbages and other brassicas (broccoli),0.51,7.90,5.01,0.00055,119.4,8455.1
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,sauces & paste,0.00,6.75,0.00,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,crustaceans (shrimp/prawns),26.87,70.30,227.22,0.00297,3515.4,127259.0
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,beans and pulses (dried),1.79,5.90,17.08,0.01557,435.7,22477.4
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,other vegetables,0.53,7.90,2.27,0.00038,102.5,4911.4
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,stimulants & spices misc.,0.00,6.75,0.00,0.00000,0.0,0.0
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,onions and leeks,0.50,7.90,3.24,0.00039,14.3,932.0

In [39]:
mapping[mapping["g N lost/kg product"].isnull()]

Empty DataFrame
Columns: [ItemId, CategoryID, Description, CaseQty, CaseUOM, PakQty, PakUOM, InventoryGroup, Food Category_y, Active Total Supply Chain Emissions (kg CO2 / kg food), g N lost/kg product, Eutrophying Emissions (g PO43-eq / kg food), Land Use (m^2), Freshwater Withdrawals (L/FU), Stress-Weighted Water Use (L/FU)]
Index: []

In [40]:
mapping[mapping["ItemId"] == "I-4140"]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
474,I-4140,40,CILANTRO 3ct,1.0,bunch,400.0,ml,Y,other vegetables,0.53,7.9,2.27,0.00038,102.5,4911.4

In [41]:
mapping["CategoryID"].isnull().sum()

np.int64(0)

### Manully Adjust Footprint Factor for Specific Items

In [42]:
# # For Manual_Factor: dataframe with items that adjusted GHGe factor manually.
# # It takes the id for Manual_Factor for the index being iterated and if it is equal to item id of mapping dataframe then it sets
# # the values of the columns to the manually adjusted values
# # Note: the values for the columns in mapping DataFrame is adjusted and not Manual_Factor DataFrame
# for index, row in Manual_Factor.iterrows():
#     itemId = Manual_Factor.loc[index, 'ItemId']
#     ghge = Manual_Factor.loc[index, 'Active Total Supply Chain Emissions (kg CO2 / kg food)']
#     nitro = Manual_Factor.loc[index, 'g N lost/kg product']
#     eutro = Manual_Factor.loc[index, 'Eutrophying Emissions (g PO43-eq / kg food)']
#     water = Manual_Factor.loc[index, 'Freshwater Withdrawals (L/FU)']
#     land = Manual_Factor.loc[index, 'Land Use (m^2)']
#     str_water = Manual_Factor.loc[index, 'Stress-Weighted Water Use (L/FU)']
#     mapping.loc[mapping['ItemId'] == itemId, 'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = ghge
#     mapping.loc[mapping['ItemId'] == itemId, 'g N lost/kg product'] = nitro
#     mapping.loc[mapping['ItemId'] == itemId, 'Eutrophying Emissions (g PO43-eq / kg food)'] = eutro
#     mapping.loc[mapping['ItemId'] == itemId, 'Freshwater Withdrawals (L/FU)'] = water
#     mapping.loc[mapping['ItemId'] == itemId, 'Stress-Weighted Water Use (L/FU)'] = str_water
#     mapping.loc[mapping['ItemId'] == itemId, 'Land Use (m^2)'] = land

In [43]:
mapping.drop_duplicates(subset = ['ItemId'], inplace=True)
mapping.dtypes

ItemId                                                     object
CategoryID                                                  int64
Description                                                object
CaseQty                                                   float64
CaseUOM                                                    object
PakQty                                                    float64
PakUOM                                                     object
InventoryGroup                                             object
Food Category_y                                            object
Active Total Supply Chain Emissions (kg CO2 / kg food)    float64
g N lost/kg product                                       float64
Eutrophying Emissions (g PO43-eq / kg food)               float64
Land Use (m^2)                                            float64
Freshwater Withdrawals (L/FU)                             float64
Stress-Weighted Water Use (L/FU)                          float64
dtype: object

In [44]:
mapping.shape

(582, 15)

In [45]:
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-1971,35,LIMES,0.25,ea,1.0,ea,N,citrus fruit,0.39,2.70,2.24,0.00086,82.7,4662.7
1,I-8228,55,Grey Goose 1.14L,1.00,fl oz,1.0,fl oz,N,water & beverages,0.00,0.00,0.00,0.00000,1.0,1.0
2,I-15803,31,Red Bull Watermelon,1.00,can,1.0,can,N,other fruits,1.05,2.70,2.43,0.00089,153.5,9533.1
3,I-5505,36,Lettuce - Romaine,0.25,HEAD,1.0,HEAD,N,cabbages and other brassicas (broccoli),0.51,7.90,5.01,0.00055,119.4,8455.1
4,I-8667,58,ITEM GARLIC MAYO,2.00,fl oz,1.0,ml,N,sauces & paste,0.00,6.75,0.00,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,I-5577,13,SHRIMP Butterfly Coconut 13-15,175.00,g,175.0,g,Y,crustaceans (shrimp/prawns),26.87,70.30,227.22,0.00297,3515.4,127259.0
578,I-5578,17,Bean Vermiceli Noodle Fortune,6.00,g,6.0,g,Y,beans and pulses (dried),1.79,5.90,17.08,0.01557,435.7,22477.4
579,I-5579,40,Lettuce Green Leaf Fillet,50.00,g,50.0,g,Y,other vegetables,0.53,7.90,2.27,0.00038,102.5,4911.4
580,I-5580,54,SPICE Piri Piri seasoning mix,20.00,g,20.0,g,Y,stimulants & spices misc.,0.00,6.75,0.00,0.00000,0.0,0.0
581,I-5581,39,ONION RING BTD TEMPURA BEEFEAT,0.50,lb,226.8,g,Y,onions and leeks,0.50,7.90,3.24,0.00039,14.3,932.0

In [46]:
mapping[mapping["ItemId"] == "I-1874"]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
16,I-1874,38,GARLIC WHOLE PEELED,200.0,g,30.0,oz,N,root vegetables,0.43,7.9,1.61,0.00033,28.4,929.2

In [47]:
# mapping.to_csv("mapping.csv")

In [48]:
ingredients = pd.read_csv("data/preprocessed/AMS_data/Ingredients_List.csv")
ingredients

   IngredientId    Qty      Uom   Recipe
0       P-10125    1.0       ea  R-10977
1        P-7216    1.0       ea  R-10977
2        I-4212  250.0        g  R-10977
3        I-2119  150.0       ml  R-10977
4        I-4163   10.0      LBS  P-10125
5        I-1635    1.0       ea  P-10125
6        I-4184  250.0       ml  P-10125
7        I-2929  500.0        g  P-10125
8        P-7216   10.0       ea  P-10125
9        I-4212    2.0      bag  P-10125
10       I-4127    1.0       ea   P-7216
11       I-6865    3.0  oz (wt)   P-7216
12       I-1874    1.0  oz (wt)   P-7216
13       I-2119   30.0       ml   P-7216
14       I-1958  400.0       ml   P-7216
15       I-2366   50.0        g   P-7216
16       I-2436   50.0       ml   P-7216
17       I-2323    1.0      tsp   P-7216

In [49]:
map_list = mapping["ItemId"].unique()
absent_list = []

for item in ingredients["IngredientId"].unique():
    if item not in map_list and not item.startswith("P-"):
        absent_list.append(item)

# absent_list contains the IngredientIds that are not present in mapping but are present in the ingredients DataFrame
print(absent_list)

[]

In [50]:
for x in absent_list:
    print(ingredients[ingredients["IngredientId"] == x])

In [51]:
# Converts mapping DataFrame to the Mapping.csv file
path = os.path.join(os.getcwd(), "data", "mapping", "AMS_data", "Mapping.csv")
mapping.to_csv(path, index = False, header = True)