![](ubc_header.png)

# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

****

## Part I: Data Preprocessing

## Set up and Import Libraries

In [1]:
#pip install -r requirements.txt

In [2]:
import pandas as pd
import glob
import os
import xml.etree.ElementTree as et

In [3]:
# # RUN ONLY ONCE
# # os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

****

## Load Data Files

### Set Data File Path

In [4]:
# Select data file path for the chosen venue and time range where the recipes data stored
RESTAURANT_FOLDER_NAME = "PHO_REAL" 

# List all the files in the respective restaurant folder
filepath_list = glob.glob(os.path.join(os.getcwd(), "data", "raw", RESTAURANT_FOLDER_NAME, "*.oc"))

filepath_list

['/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25/data/raw/PHO_REAL/PHO_REAL_11_mar_2025.oc.oc']

### Import Items List

In [5]:
# Read items.xml files in the filepath_list and construct a dataframe
ItemId = []
Description = []
CaseQty = []
CaseUOM = []
PakQty = []
PakUOM = []
InventoryGroup = []


# from the items xml file, findtext of CaseQty, CaseUOM, PakQty, PakUOM, and InventoryGroup
# then append it on the lists above

for filepath in filepath_list:
    path = filepath + '/Items.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for item in xtree.iterfind('Item'):
            ItemId.append(item.attrib['id'])
            Description.append(item.findtext('Description'))
            CaseQty.append(item.findtext('CaseQty'))
            CaseUOM.append(item.findtext('CaseUOM'))
            PakQty.append(item.findtext('PakQty'))
            PakUOM.append(item.findtext('PakUOM'))
            InventoryGroup.append(item.findtext('InventoryGroup'))

            
# Create a dataframe from the lists created above.
        
Items = pd.DataFrame({'ItemId': ItemId, 'Description': Description, 'CaseQty': CaseQty, 
                      'CaseUOM': CaseUOM, 'PakQty': PakQty, 'PakUOM': PakUOM, 'InventoryGroup': InventoryGroup}
                    )

Items.drop_duplicates(inplace=True)

Items.reset_index(drop=True, inplace=True)

In [6]:
# creates a new array with unique ItemIds
all_id_list = Items["ItemId"].unique()

In [7]:
# Gives you the list of breads
breadlist = []


# If the items in the Items list is a "LOAF", "SANDWICH", or "BREAD" then we should add it in the breadlist
# We append it onto the breadlist at position row["ItemId"]
for ind, row in Items.iterrows():
    if ("LOAF" or "SANDWICH" "BREAD") in row["Description"]:
        breadlist.append(row["ItemId"])

breadlist

[]

In [8]:
Items = Items[~Items["InventoryGroup"].isin(["DISPOSABLES", "SUPPLY"])]

In [9]:
# Based on info below there are 486 rows and 7 columns
Items.shape

(43, 7)

In [10]:
Items.dtypes

ItemId            object
Description       object
CaseQty           object
CaseUOM           object
PakQty            object
PakUOM            object
InventoryGroup    object
dtype: object

In [11]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Items_List.csv")
Items.to_csv(path, index = False, header = True)

### Import Ingredients List

In [12]:
# Read ingredients.xml files in the filepath_list and construct a dataframe
IngredientId = []
Conversion = []
InvFactor = []
Qty = []
Recipe = []
Uom = []

# Using the Ingredients XML file, we extract attributes containing ingredients, conversion, invFactor, qty, recipe, and uom. 
# Then we append it onto the IngredientId, Coversion, InvFactor, Qty, Recipe, and Uom lists
# Then we create a dataframe using the lists created. 

for filepath in filepath_list:
    path = filepath + '/Ingredients.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Ingredient'):
            IngredientId.append(x.attrib['ingredient'])
            Conversion.append(x.attrib['conversion'])
            InvFactor.append(x.attrib['invFactor'])
            Qty.append(x.attrib['qty'])
            Recipe.append(x.attrib['recipe'])
            Uom.append(x.attrib['uom'])
    
Ingredients = pd.DataFrame({'IngredientId': IngredientId, 'Qty': Qty,'Uom': Uom, 'Conversion': Conversion, 
                      'InvFactor': InvFactor,'Recipe': Recipe}).drop_duplicates()
Ingredients.drop_duplicates(subset=["IngredientId", "Recipe"], inplace=True)

Ingredients.reset_index(drop=True, inplace=True)

In [13]:
# This will output the IngredientId on the right side and the number of times the ingredient appears in the Ingredients
# dataframe on the left side. 

# The duplicated() method returns a Series with True and False values that describe which rows in the DataFrame are 
# duplicated and not.

check = Ingredients["IngredientId"].duplicated()

# The line below tells us at which index is the ingredient duplicated. For example I-4598 exists on index 2 of the dataframe and
# then again on index 8. So duplicate is first true on index 8, which is why it is printed below. It also appears in a below 
# index so it is printed again with that index number. 
Ingredients["IngredientId"][check]

10      I-5983
13      I-3660
14      I-3698
15      I-5983
19      I-5983
        ...
213    P-14709
214    P-26514
215    P-55508
216    P-68101
217    P-68113
Name: IngredientId, Length: 151, dtype: object

In [14]:
Ingredients

    IngredientId       Qty Uom  Conversion InvFactor   Recipe
0         I-3660     2.500   L  0.88028169    0.0006  P-14709
1         I-3698     2.500   L  1.00000000    0.0006  P-14709
2         I-4574  2270.000   g  0.00220462    0.5044  P-14709
3         I-4634  2270.000   g  0.00220462    0.5044  P-14709
4         I-5983     2.500   L  1.00000000    0.0006  P-14709
..           ...       ...  ..         ...       ...      ...
213      P-14709    10.000   g  1.00000000    1.0000  R-75763
214      P-26514     3.000   g  1.00000000    1.0000  R-75763
215      P-55508     3.000   g  1.00000000    1.0000  R-75763
216      P-68101    45.000  ml  0.00100000    1.0000  R-75763
217      P-68113    50.000   g  1.00000000    1.0000  R-75763

[218 rows x 6 columns]

In [15]:
Items

,ItemId,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-72014,BALL BEEF BO VIEN^,1.000,ea,1.000,ea,MEAT
1,I-72015,BALL CHICKEN GA VIEN^,1.000,ea,1.000,ea,POULTRY
2,I-3130,BASE BEEF*CONC LIQ G/FREE^,9.000,bottle,946.000,ml,FOOD - GROCERY
3,I-72023,BASE SOUP PHO BEEF VIET ^,24.000,pak,284.000,g,FOOD - GROCERY
4,I-72022,BASE SOUP PHO VEGETARIAN,24.000,pak,284.000,g,FOOD - GROCERY
5,I-3141,BASE VEG*CONC LIQ G/FREE^,4.000,bottle,946.000,ml,FOOD - GROCERY
6,I-11556,BEANS EDAMAME KERNELS^,20.000,pak,0.400,Kg,PRODUCE
7,I-37002,BEEF INSIDE ROUND SHAVED,9.000,Kg,1000.000,g,MEAT
11,I-43543,CABBAGE RED ^,1.000,each,1.000,ea,PRODUCE
12,I-4574,CARROTS SHREDDED 1/8 (COARSE)^,5.000,lb,1.000,lb,PRODUCE
13,I-11620,CHICKEN BREAST BENTO,2.000,pak,2.200,Kg,MEAT
14,I-72089,CHICKEN BRST STRP CKD^,2.000,bag,2.000,Kg,"PACKAGED BEER, CIDER"
16,I-4626,CUCUMBER BC^,3.000,CT,1.000,CT,PRODUCE
18,I-4634,DAIKON MATCH STICK US^,5.000,lb,1.000,lb,PRODUCE
20,I-4341,HERB CILANTRO BUNCH 30CT^,30.000,CT,1.000,CT,PRODUCE
21,I-4918,HERB THAI BASIL BC^,1.000,lb,1.000,lb,PRODUCE
22,I-1759,JUICE LIME SUN ORCHARD^,1.000,JUG,64.000,fl oz,BEVERAGE
23,I-4677,LETTUCE GREEN LEAF (LINER) US^,24.000,CT,1.000,CT,PRODUCE
24,I-4693,LETTUCE ICEBERG (LINER)US,3.000,CT,1.000,CT,PRODUCE
30,I-7179,LIMES MX 3LB^,5.000,lb,1.000,lb,PRODUCE
32,I-19295,NOODLES RICE MED,30.000,lb,1.000,lb,FOOD - GROCERY
33,I-19464,NOODLES RICE VERMICELLI,30.000,pak,400.000,g,FOOD - GROCERY
34,I-32431,OC,1.000,ea,1.000,ea,ZDONT USE FOOD
35,I-3391,OIL SESAME 100% PURE,1.000,pak,1.800,L,FOOD - GROCERY
36,I-6815,ONIONS FRIED CRISPY^,15.000,pak,400.000,g,FOOD - GROCERY
37,I-10149,ONIONS GREEN BUNCHED,1.000,BUNCH,1.000,BUNCH,PRODUCE
38,I-4678,ONIONS GREEN TRIM (ICELESS) US,2.000,lb,1.000,lb,PRODUCE
39,I-4754,ONIONS JUMBO US,50.000,lb,1.000,lb,PRODUCE
40,I-4752,"ONIONS RED SLICED 1/8 US""^",5.000,lb,1.000,lb,PRODUCE
41,I-4753,"ONIONS SLICED 1/8 US""^",5.000,lb,1.000,lb,PRODUCE
42,I-23748,RICE PAPER WRAP,44.000,pak,340.000,g,FOOD - GROCERY
43,I-72016,ROLL PORK CHAU LAU^,1.000,ea,1.000,ea,MEAT
44,I-6026,SALT KOSHER WINDSOR^,16.320,Kg,1000.000,g,SPICES
45,I-9379,SAUCE CHILI*HOT SRIRACHA BOTL^,12.000,bottle,0.714,L,FOOD - GROCERY
46,I-3517,SAUCE FISH*,12.000,bottle,23.000,fl oz,FOOD - GROCERY
47,I-10864,SAUCE HOISIN GOLDEN DRAGON,2.000,JUG,4.000,L,FOOD - GROCERY
48,I-3540,SAUCE SAMBAL OELEK,4.000,jar,3.500,L,FOOD - GROCERY
49,I-3545,SAUCE SOY G/FREE^,1.000,JUG,1.890,L,FOOD - GROCERY
50,I-4509,SPROUTS BEAN*BC^,5.000,lb,1.000,lb,PRODUCE
51,I-61314,SS TOFU FIRM 500GM,12.000,pak,1.000,pak,FOOD - GROCERY
52,I-3660,SUGAR GRANULATED*FINE^,10.000,Kg,1.000,Kg,FOOD - GROCERY
53,I-3698,VINEGAR WHITE PURE DISTILLED,12.000,bottle,0.500,L,FOOD - GROCERY
54,I-5983,WATER FOR RECIPES,1.000,L,1.000,L,BEVERAGE

In [16]:
Ingredients.shape

(218, 6)

In [17]:
Ingredients.dtypes

IngredientId    object
Qty             object
Uom             object
Conversion      object
InvFactor       object
Recipe          object
dtype: object

In [18]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Ingredients_List.csv")
Ingredients.to_csv(path, index = False, header = True)

### Import Preps List

In [19]:
# Read preps.xml files in the filepath_list and construct a dataframe
PrepId = []
Description = []
PakQty = []
PakUOM = []
InventoryGroup = []


# Here we do the same thing for the Preps XML file where we find the columns using attrib function and then append it onto
# the dataframe called Preps. 

for filepath in filepath_list:
    path = filepath + '/Preps.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Prep'):
            PrepId.append(x.attrib['id'])
            Description.append(x.findtext('Description'))
            PakQty.append(x.findtext('PakQty'))
            PakUOM.append(x.findtext('PakUOM'))
            InventoryGroup.append(x.findtext('InventoryGroup'))
    
Preps = pd.DataFrame({'PrepId': PrepId, 'Description': Description,
                  'PakQty': PakQty, 'PakUOM':PakUOM, 'InventoryGroup': InventoryGroup}).drop_duplicates()
preps_columns = Preps.columns
Preps.drop_duplicates(subset=["PrepId"], inplace=True)

Preps.reset_index(drop=True, inplace=True)

In [20]:
Preps

     PrepId                Description    PakQty PakUOM InventoryGroup
0   P-71589             PHO BROTH|Beef    17.000      L
1   P-71997      PHO BROTH|Veg/Chicken    17.000      L
2   P-68113       PHO COOKED|Vermiclli   600.000      g
3   P-14709  PHO PICKLE|Carrot & Dikon  4500.000      g
4   P-68101        PHO SAUCE|Nuoc Cham    16.000      L
5   P-72055         PREP|Sliced Onion   3000.000      g
6   P-71610    Prep|Vietnamese Edamame     2.000     Kg
7   P-72038           SAUCE|Sesame Soy     1.500      L
8   P-65968    Soak|Rice noodle medium   800.000      g
9   P-26514       YIELD|HERB|Cilantro     55.000      g
10  P-55508    YIELD|HERB|Fresh Basil    225.000      g
11  P-19236     YIELD|VEG|Green Onion    920.000      g

In [21]:
# This tells us that there are not any duplicates in the Preps dataframe. There is a different process|ingredient pair for 
# all the recipes. 
check = Preps["PrepId"].duplicated().any()
print(check)

False

In [22]:
# There are 546 rows and 5 columns
Preps.shape

(12, 5)

In [23]:
Preps.dtypes

PrepId            object
Description       object
PakQty            object
PakUOM            object
InventoryGroup    object
dtype: object

In [24]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Preps_List.csv")
Preps.to_csv(path, index = False, header = True)

### Import Products List

In [25]:
# Read products.xml files in the filepath_list and construct a dataframe
ProdId = []
Description = []
SalesGroup = []

# From the XML file for products append the id into ProdId, description into Description, and SalesGroup into SalesGroup list.
# Make a dataframe out of the 3 lists
# Then also drop the duplicates in the Products dataframe

for filepath in filepath_list:
    path = filepath + '/Products.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Prod'):
            ProdId.append(x.attrib['id'])
            Description.append(x.findtext('Description'))
            SalesGroup.append(x.findtext('SalesGroup'))
        
Products = pd.DataFrame({'ProdId': ProdId, 'Description': Description, 'SalesGroup': SalesGroup})
Products.drop_duplicates(inplace=True)

Products.reset_index(drop=True, inplace=True)

In [26]:
Products

     ProdId                     Description SalesGroup
0   R-68117         PHO VERMICELLI|Chicken        FOOD
1   R-71611        PHO VERMICELLI|Pork Roll       FOOD
2   R-71609             PHO VERMICELLI|Tofu       FOOD
3   R-71612                PHO VIET|Edamame       FOOD
4   R-71613  PHO VIET|Pickle Carrot & Daiko       FOOD
5   R-75762     PHO VIET|Salad Roll Chicken       FOOD
6   R-75763        PHO VIET|Salad Roll Pork       FOOD
7   R-71615        PHO VIET|Salad Roll Tofu       FOOD
8   R-72884            PHO VIET|Spring Roll       FOOD
9   R-71604                   PHO|Beef Ball       FOOD
10  R-65881                   PHO|Beef Rare       FOOD
11  R-71607                     PHO|Chicken       FOOD
12  R-71608                PHO|Chicken Ball       FOOD
13  R-71606                         PHO|VEG       FOOD

In [27]:
Products.dtypes

ProdId         object
Description    object
SalesGroup     object
dtype: object

In [28]:
Products.shape

(14, 3)

In [29]:
Products.dtypes

ProdId         object
Description    object
SalesGroup     object
dtype: object

In [30]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Products_List.csv")
Products.to_csv(path, index = False, header = True)

### Import Conversions List

In [31]:
# Read conventions.xml files in the filepath_list and construct a dataframe
ConversionId = []
Multiplier = []
ConvertFromQty = []
ConvertFromUom = []
ConvertToQty = []
ConvertToUom = []

# From the XML file for Conversions append the id into ConversionId, multiplier into Multiplier, ConvertFrom->qty into 
# ConvertFromQty,ConvertFrom->uom into ConvertFromUom, ConvertTo->qty into ConvertToQty and and ConvertTo->uom into the
# CovertToUom list. 
# Make a dataframe out of the 3 lists
# Then also drop the duplicates in the Products dataframe


for filepath in filepath_list:
    path = filepath + '/Conversions.xml'
    if os.path.isfile(path):
        xtree = et.parse(path)
        xroot = xtree.getroot()
        for x in xtree.iterfind('Conversion'):
            ConversionId.append(x.attrib['id'])
            Multiplier.append(x.attrib['multiplier'])
            ConvertFromQty.append(x.find('ConvertFrom').attrib['qty'])
            ConvertFromUom.append(x.find('ConvertFrom').attrib['uom'])
            ConvertToQty.append(x.find('ConvertTo').attrib['qty'])
            ConvertToUom.append(x.find('ConvertTo').attrib['uom'])
    
    
Conversions = pd.DataFrame({'ConversionId': ConversionId, 'Multiplier': Multiplier, 'ConvertFromQty': ConvertFromQty,
                           'ConvertFromUom': ConvertFromUom, 'ConvertToQty': ConvertToQty, 'ConvertToUom': ConvertToUom}
                          ).drop_duplicates()

Conversions.reset_index(drop=True, inplace=True)

In [32]:
# Here we can see for example that to convert 1.14 L to 1 L the multiplier is 0.877 since 1/1.14 = 0.877
Conversions

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,,1.00000000,1.0000,XXX,1.0000,L
1,,0.87719298,1.0000,1.14L,1.1400,L
2,,0.66666667,1.0000,1.5L,1.5000,L
3,,0.57142857,1.0000,1.75 L,1.7500,L
4,,0.50000000,1.0000,2L,2.0000,L
...,...,...,...,...,...,...
57,I-5983,0.00100000,1.0000,L,1000.0000,g
58,I-10149,0.04000000,1.0000,BUNCH,25.0000,g
59,I-10149,0.01000000,1.0000,CT,100.0000,g
60,I-43543,0.04347826,1.0000,leaf,23.0000,g
61,I-43543,0.00088183,1.0000,ea,1134.0000,g

In [33]:
all_id_list = Items["ItemId"].unique()
all_conv_list = Conversions["ConversionId"].unique()

print("All unique IDs list\n")
print(all_id_list)
print("\n")
print("All unique Conversions list\n")
print(all_conv_list)

All unique IDs list

['I-72014' 'I-72015' 'I-3130' 'I-72023' 'I-72022' 'I-3141' 'I-11556'
 'I-37002' 'I-43543' 'I-4574' 'I-11620' 'I-72089' 'I-4626' 'I-4634'
 'I-4341' 'I-4918' 'I-1759' 'I-4677' 'I-4693' 'I-7179' 'I-19295' 'I-19464'
 'I-32431' 'I-3391' 'I-6815' 'I-10149' 'I-4678' 'I-4754' 'I-4752' 'I-4753'
 'I-23748' 'I-72016' 'I-6026' 'I-9379' 'I-3517' 'I-10864' 'I-3540'
 'I-3545' 'I-4509' 'I-61314' 'I-3660' 'I-3698' 'I-5983']


All unique Conversions list

['' 'I-1759' 'I-3391' 'I-3517' 'I-3545' 'I-3660' 'I-3698' 'I-4341'
 'I-4574' 'I-4626' 'I-4693' 'I-5983' 'I-10149' 'I-43543']

In [34]:
# Here we have the number of items in the list that are a part of the "all_id_list" but not part of the "all_conv_list"
missing_conv_id = []

for item in all_id_list:
    if item not in all_conv_list:
        missing_conv_id.append(item)
        
missing_conv_id
print(len(missing_conv_id))

30

In [35]:
Conversions.shape

(62, 6)

In [36]:
Conversions.dtypes

ConversionId      object
Multiplier        object
ConvertFromQty    object
ConvertFromUom    object
ConvertToQty      object
ConvertToUom      object
dtype: object

In [37]:
# Save the dataframe to csv
path = os.path.join(os.getcwd(), "data", "preprocessed", "Conversions_List.csv")
Conversions.to_csv(path, index = False, header = True)

***
## Data Summary

In [38]:
# Summary of raw data imported for evaluation
# Here we have a summary of the number of items, preps, ingredients, products, conversions

datasum = pd.DataFrame([Items.shape, Preps.shape, Ingredients.shape, Products.shape, Conversions.shape],
                       columns = ['count', 'columns'], 
                       index = ['Items', 'Preps', 'Ingredients', 'Products', 'Conversions'])
datasum

             count  columns
Items           43        7
Preps           12        5
Ingredients    218        6
Products        14        3
Conversions     62        6