# Climate-Friendly Food Systems (CFFS) Labelling Project

### The University of British Columbia

***

## Part III: Update Information and Mapping

## Set up and Import Libraries

In [1]:
#pip install -r requirements.txt

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os
import csv
from itertools import islice
from decimal import Decimal
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse
from datetime import datetime

In [3]:
# RUN ONLY ONCE
# os.chdir is used to change the current directory to the specified path
os.chdir("../") # Sets path to the repo folder as it is one level above where this file exists!
path = os.getcwd()
print(path)

/Users/ankurbhardwaj/Desktop/SEEDS/CFFS_Label_2024_25

***
## Import Preprocessed Datasets

In [4]:
# Creates a DataFrame from reading a csv file 
Preps = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "Preps_Unit_Cleaned.csv"))
Preps.head()

    PrepId          Description  PakQty PakUOM InventoryGroup   StdQty StdUom
0  P-21818        BREAD|Garlic*    6.00     ea            NaN      6.0     ea
1  P-18945        COOKED|Farro*   18.18     Kg            NaN  18180.0      g
2  P-74119       COOKED|Gnocchi    8.00     Kg            NaN   8000.0      g
3  P-27185  COOKED|Pasta Short*   10.00     Kg            NaN  10000.0      g
4  P-18863   Cooked|Spaghetti*    18.18     Kg      CK - FOOD  18180.0      g

In [5]:
# Creates a DataFrame from reading a csv file 
ghge_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "ghge_factors.csv"))
ghge_factors.head()

,Category ID,Food Category,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,1,beef & buffalo meat,85.5822
1,2,lamb/mutton & goat meat,39.7200
2,3,pork (pig meat),12.3100
3,4,"poultry (chicken, turkey)",9.8700
4,5,butter,16.1300

In [6]:
# Creates a DataFrame from reading a csv file 
nitro_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "nitrogen_factors.csv"))
nitro_factors.head()

eutro_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "eutrophying_factors.csv"))
eutro_factors.head()

,Category ID,Food Category,Eutrophying Emissions (g PO43-eq / kg food)
0,1,beef & buffalo meat,314.8248
1,2,lamb/mutton & goat meat,97.1300
2,3,pork (pig meat),76.3800
3,4,"poultry (chicken, turkey)",48.7000
4,5,butter,54.5300

In [7]:
# Creates a DataFrame from reading a csv file 
water_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "water_factors.csv"))
water_factors.head()

,Category ID,Food Category,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,1,beef & buffalo meat,1716.451,52597.767
1,2,lamb/mutton & goat meat,1802.800,141925.000
2,3,pork (pig meat),1795.800,66867.400
3,4,"poultry (chicken, turkey)",660.000,14177.900
4,5,butter,3216.720,101316.490

In [8]:
# Creates a DataFrame from reading a csv file 
land_factors = pd.read_csv(os.path.join(os.getcwd(), "data", "external", "land_factors.csv"))
land_factors.rename(columns={'km^2 land use/kg product': 'Land Use (m^2)'}, inplace=True)
land_factors['Land Use (m^2)'] *= 1000
land_factors.head()

   Category ID              Food Category  Land Use (m^2)
0            1        beef & buffalo meat        0.266786
1            2    lamb/mutton & goat meat        0.369810
2            3            pork (pig meat)        0.017360
3            4  poultry (chicken, turkey)        0.012220
4            5                     butter        0.045830

In [9]:
# Load current Items List with assigned Emission Factors Category ID
Items_Assigned = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "Items_List_Assigned.csv"))
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN

In [10]:
new_items = pd.read_csv("data/mapping/new items added/New_Items_2025/New_Items_Added_2025-08-14.csv")
new_items

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-73832,1,BEEF FLANK COV GRASS FED PR,1.0,Kg,1.0,Kg,MEAT
1,I-4522,38,BEETS CANDY CANE US,25.0,lb,1.0,lb,PRODUCE
2,I-73421,24,CIABATTA SLI*RECTANGLE,1.0,cs,48.0,CT,BREAD
3,I-73854,3,"HOT DOG 6"" TWO RIVER",1.0,Kg,1.0,Kg,MEAT
4,I-3087,24,NOODLES CHOW*MEIN,6.0,BG,5.0,lb,FOOD - GROCERY
5,I-4908,18,PEAS SUGAR/SNOW CI,10.0,lb,1.0,lb,PRODUCE
6,I-75824,54,SEASONING TAJIN*CHILI LIME LI,12.0,SM SKR,400.0,g,SPICES
7,I-33643,37,"TOMATOES DICED 1/4""",5.0,lb,1.0,lb,PRODUCE

In [11]:
item_nonstd = pd.read_csv("data/cleaning/Items_Nonstd.csv")
item_nonstd

Empty DataFrame
Columns: [IngredientId, Qty, Uom, Conversion, InvFactor, Recipe]
Index: []

In [12]:
preps_nonstd = pd.read_csv("data/cleaning/Preps_NonstdUom.csv")
preps_nonstd

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

In [13]:
conv_updatecov = pd.read_csv("data/cleaning/update/Conv_UpdateConv.csv")
conv_updatecov

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-67659,0.008818,1.0,each,113.398,g
1,I-28697,0.005181,1.0,ea,193.000,g
2,I-47441,0.005181,1.0,ea,193.000,g
3,I-1905,0.012500,1.0,CT,80.000,g
4,I-47440,0.005051,1.0,ea,198.000,g
...,...,...,...,...,...,...
679,I-64877,0.008850,1.0,each,113.000,g
680,I-74371,0.016667,1.0,CT,60.000,g
681,I-2161,0.006667,1.0,PTN,150.000,g
682,I-73309,0.000220,1.0,ea,4536.000,g
683,I-73421,0.007143,1.0,CT,140.000,g

In [14]:
conv_updatecov.loc[conv_updatecov["ConversionId"] == "P-54581"]

Empty DataFrame
Columns: [ConversionId, Multiplier, ConvertFromQty, ConvertFromUom, ConvertToQty, ConvertToUom]
Index: []

In [15]:
Preps.loc[Preps["PrepId"] == "P-54581"]

Empty DataFrame
Columns: [PrepId, Description, PakQty, PakUOM, InventoryGroup, StdQty, StdUom]
Index: []

# Update Conversion_Added.csv

In [16]:
conversions_added = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "Conversions_Added.csv"))
conversions_added

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,NaN,1.000000,1.0,XXX,1.00,L
1,NaN,0.877193,1.0,1.14L,1.14,L
2,NaN,0.666667,1.0,1.5L,1.50,L
3,NaN,0.571429,1.0,1.75 L,1.75,L
4,NaN,0.500000,1.0,2L,2.00,L
...,...,...,...,...,...,...
503,I-64877,0.008850,1.0,each,113.00,g
504,I-74371,0.016667,1.0,CT,60.00,g
505,I-2161,0.006667,1.0,PTN,150.00,g
506,I-73309,0.000220,1.0,ea,4536.00,g
507,I-73421,0.007143,1.0,CT,140.00,g

In [17]:
# Concatenate the DataFrames
combined_df = pd.concat([conv_updatecov, conversions_added], ignore_index=True)
combined_df

,ConversionId,Multiplier,ConvertFromQty,ConvertFromUom,ConvertToQty,ConvertToUom
0,I-67659,0.008818,1.0,each,113.398,g
1,I-28697,0.005181,1.0,ea,193.000,g
2,I-47441,0.005181,1.0,ea,193.000,g
3,I-1905,0.012500,1.0,CT,80.000,g
4,I-47440,0.005051,1.0,ea,198.000,g
...,...,...,...,...,...,...
1187,I-64877,0.008850,1.0,each,113.000,g
1188,I-74371,0.016667,1.0,CT,60.000,g
1189,I-2161,0.006667,1.0,PTN,150.000,g
1190,I-73309,0.000220,1.0,ea,4536.000,g
1191,I-73421,0.007143,1.0,CT,140.000,g

In [18]:
# Add the conv_updatecov file to the masterfile, Conversions_Added
path = os.path.join(os.getcwd(), "data", "cleaning", "Conversions_Added.csv")
combined_df.to_csv(path, index = False, header = True)

***
## Import Update Info

In [19]:
# Import list of prep that need convert uom to standard uom manually
Manual_PrepU = pd.read_csv(os.path.join(os.getcwd(), "data", "cleaning", "update", "Preps_UpdateUom.csv"))
# Here we can see that UOM examples are: each, ea, slice
Manual_PrepU.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-35132,MARINATED|Lemon & Herb Chx,185.0,ea,PREP,24050.0,g
1,P-26234,BATCH|Roasted Garlic Bread,16.0,ea,PREP,1280.0,g
2,P-26170,GRILLED|NaanBread,1.0,ea,PREP,125.0,g
3,P-16305,YIELD|Smokie (1pc),1.0,ea,NaN,112.0,g
4,P-26047,BOILED|Hard Boiled Eggs FT,50.0,ea,PREP,2500.0,g

In [20]:
# The row of the DatFrame that contains the PrepId == P-54581
Manual_PrepU.loc[Manual_PrepU["PrepId"] == "P-54581"]

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
200,P-54581,SLICE|Multigrain Bread,22.0,slice,NaN,38.0,g

In [21]:
# Select the file path for new items list with category id
New_Items_Added = pd.read_csv("data/mapping/new items added/New_Items_2025/New_Items_Added_2025-08-14.csv")
New_Items_Added.tail(15)

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-73832,1,BEEF FLANK COV GRASS FED PR,1.0,Kg,1.0,Kg,MEAT
1,I-4522,38,BEETS CANDY CANE US,25.0,lb,1.0,lb,PRODUCE
2,I-73421,24,CIABATTA SLI*RECTANGLE,1.0,cs,48.0,CT,BREAD
3,I-73854,3,"HOT DOG 6"" TWO RIVER",1.0,Kg,1.0,Kg,MEAT
4,I-3087,24,NOODLES CHOW*MEIN,6.0,BG,5.0,lb,FOOD - GROCERY
5,I-4908,18,PEAS SUGAR/SNOW CI,10.0,lb,1.0,lb,PRODUCE
6,I-75824,54,SEASONING TAJIN*CHILI LIME LI,12.0,SM SKR,400.0,g,SPICES
7,I-33643,37,"TOMATOES DICED 1/4""",5.0,lb,1.0,lb,PRODUCE

In [22]:
# Import list of items that adjusted GHGe factor manually
Manual_Factor = pd.read_csv(os.path.join(os.getcwd(), "data", "mapping", "Manual_Adjust_Factors.csv"))
Manual_Factor.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU),Land Use (m^2),Eutrophying Emissions (g PO43-eq / kg food)
0,I-52090,59,BURGER BEEF & MUSHROOM HALAL,1.0,cs,48.00,CT,MEAT,25.00894,200.86,1038.84,37961.2,0.0,0
1,I-45558,59,Prep-Vegan Parmesan,1000.0,g,1.00,g,PRODUCTION FOOD,3.85686,0.00,0.00,0.0,0.0,0
2,I-3352,59,MAYONNAISE PAIL TFC 4L,2.0,each,4.00,L,FOOD - GROCERY,3.55000,0.00,0.00,0.0,0.0,0
3,I-3223,59,COCONUT MILK 17/19% MILK FAT,6.0,LG CAN,2.84,L,FOOD - GROCERY,3.50000,0.00,1.00,1.0,0.0,0
4,I-2898,59,MUSTARD DIJON WINE FLEUR,6.0,jar,1.00,Kg,FOOD - GROCERY,3.32600,0.00,0.00,0.0,0.0,0

### Update Correct Uom for Preps

In [23]:
# Update prep list with manually adjusted uom
for index, row in Manual_PrepU.iterrows():
    PrepId = Manual_PrepU.loc[index, 'PrepId']
    qty = Manual_PrepU.loc[index, 'StdQty']
    uom = Manual_PrepU.loc[index, 'StdUom']
    Preps.loc[Preps['PrepId'] == PrepId, 'StdQty'] = qty
    Preps.loc[Preps['PrepId'] == PrepId, 'StdUom'] = uom

In [24]:
Preps.drop_duplicates(subset=['PrepId'], inplace=True,)

In [25]:
Preps.shape

(21, 7)

In [26]:
Preps.head()

,PrepId,Description,PakQty,PakUOM,InventoryGroup,StdQty,StdUom
0,P-21818,BREAD|Garlic*,6.00,ea,NaN,808.001016,g
1,P-18945,COOKED|Farro*,18.18,Kg,NaN,18180.000000,g
2,P-74119,COOKED|Gnocchi,8.00,Kg,NaN,8000.000000,g
3,P-27185,COOKED|Pasta Short*,10.00,Kg,NaN,10000.000000,g
4,P-18863,Cooked|Spaghetti*,18.18,Kg,CK - FOOD,18180.000000,g

In [27]:
path = os.path.join(os.getcwd(), "data", "cleaning", "Preps_List_Cleaned.csv")
Preps.to_csv(path, index = False, header = True)

In [28]:
Items_Assigned.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN

In [29]:
New_Items_Added.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup
0,I-73832,1,BEEF FLANK COV GRASS FED PR,1.0,Kg,1.0,Kg,MEAT
1,I-4522,38,BEETS CANDY CANE US,25.0,lb,1.0,lb,PRODUCE
2,I-73421,24,CIABATTA SLI*RECTANGLE,1.0,cs,48.0,CT,BREAD
3,I-73854,3,"HOT DOG 6"" TWO RIVER",1.0,Kg,1.0,Kg,MEAT
4,I-3087,24,NOODLES CHOW*MEIN,6.0,BG,5.0,lb,FOOD - GROCERY

### Import List of New Items with Emission Factors Category ID Assigned

In [30]:
frames = [Items_Assigned, New_Items_Added]
Items_Assigned_Updated = pd.concat(frames).reset_index(drop=True, inplace=False).drop_duplicates()
Items_Assigned_Updated.head()

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN

In [31]:
Items_Assigned_Updated

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN
...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,NaN
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,NaN
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,NaN
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,NaN
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,NaN

In [32]:
Items_Assigned_Updated.shape

(3176, 9)

In [33]:
# Double brackets used to specify the column as a dataframe and not a series
# converting the 'CategoryID' column in the Items_Assigned_Updated dataframe to numeric data type using the pd.to_numeric()
# use the apply column to apply the coversion to the entire column
Items_Assigned_Updated[['CategoryID']] = Items_Assigned_Updated[['CategoryID']].apply(pd.to_numeric)

In [34]:
Items_Assigned_Updated

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN
...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,NaN
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,NaN
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,NaN
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,NaN
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,NaN

In [35]:
path = os.path.join(os.getcwd(), "data", "mapping", "Items_List_Assigned.csv")
Items_Assigned_Updated.to_csv(path, index = False, header = True)

## Mapping Items to Footprint Factors

In [36]:
Items_Assigned_Updated

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN
...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,NaN
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,NaN
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,NaN
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,NaN
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,NaN

In [37]:
# DEFINITION OF MAPPING: assigning certain attributes to data points based on criteria or predefined rules.

# Map GHG footprint factors
# merges two data frames Items_Assigned_Updated and ghge_factors on the columns CategoryID and Category ID, respectively. The 
# resulting data frame is stored in mapping.

# how='left' specifies that a left join is done between Items_Assigned_Updated and ghge_factors.
# left_on='CategoryID' specifies that the join condition for Items_Assigned_Updated should be based on the 'CategoryID' column.
# right_on='Category ID' specifies that the join condition for ghge_factors should be based on the 'Category ID' column.

mapping = pd.merge(Items_Assigned_Updated, ghge_factors.loc[:,['Category ID','Food Category','Active Total Supply Chain Emissions (kg CO2 / kg food)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')
# if row in mapping has CategoryId == NaN then it assigns the value of the column Active Total Supply Chain Emissions (kg CO2 / kg food)
# to zero
for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = 0
# drops the columns Category ID and Food Category
display(mapping)
mapping = mapping.drop(columns=['Category ID', 'Food Category_x'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_x,Category ID,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,NaN,1,beef & buffalo meat,85.5822
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,NaN,1,beef & buffalo meat,85.5822
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,NaN,1,beef & buffalo meat,85.5822
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,NaN,1,beef & buffalo meat,85.5822
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,NaN,1,beef & buffalo meat,85.5822
...,...,...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,NaN,3,pork (pig meat),12.3100
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,NaN,24,"wheat/rye (bread, pasta, baked goods)",1.5700
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,NaN,18,peas,0.9800
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,NaN,54,stimulants & spices misc.,0.0000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,NaN,37,tomatoes,2.0900

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822
...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,pork (pig meat),12.3100
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,"wheat/rye (bread, pasta, baked goods)",1.5700
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,peas,0.9800
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,stimulants & spices misc.,0.0000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,tomatoes,2.0900

In [38]:
# Map nitrogen footprint factors
mapping = pd.merge(mapping, nitro_factors.loc[:,['Category ID','Food Category','g N lost/kg product']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'g N lost/kg product'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])


# Map eutrophying footprint factors
mapping = pd.merge(mapping, eutro_factors.loc[:,['Category ID','Food Category','Eutrophying Emissions (g PO43-eq / kg food)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Eutrophying Emissions (g PO43-eq / kg food)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248
...,...,...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,pork (pig meat),12.3100,132.80,76.3800
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,"wheat/rye (bread, pasta, baked goods)",1.5700,14.80,7.1600
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,peas,0.9800,5.90,7.5200
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,stimulants & spices misc.,0.0000,6.75,0.0000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,tomatoes,2.0900,7.90,7.5100

In [39]:
# Map land footprint factors
mapping = pd.merge(mapping, land_factors.loc[:,['Category ID','Food Category','Land Use (m^2)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Land Use (m^2)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,pork (pig meat),12.3100,132.80,76.3800,0.017360
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,"wheat/rye (bread, pasta, baked goods)",1.5700,14.80,7.1600,0.003850
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,peas,0.9800,5.90,7.5200,0.007460
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,stimulants & spices misc.,0.0000,6.75,0.0000,0.000000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,tomatoes,2.0900,7.90,7.5100,0.000800

In [40]:
# Map water footprint factors
# mapping: DataFrame that is used to assign sustainability-related factors (greenhouse gas emissions, nitrogen loss, and 
# water footprint) to food items based on their category and other attributes. 
mapping = pd.merge(mapping, water_factors.loc[:,['Category ID','Food Category','Freshwater Withdrawals (L/FU)', 'Stress-Weighted Water Use (L/FU)']], 
                  how = 'left',
                  left_on = 'CategoryID', 
                  right_on = 'Category ID')

for index in mapping.index:
    if np.isnan(mapping.loc[index,'Category ID']):
        mapping.loc[index,'Freshwater Withdrawals (L/FU)'] = 0
        mapping.loc[index,'Stress-Weighted Water Use (L/FU)'] = 0

mapping = mapping.drop(columns=['Category ID', 'Food Category'])
mapping.drop_duplicates(subset=["ItemId"], inplace=True)
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,pork (pig meat),12.3100,132.80,76.3800,0.017360,1795.800,66867.400
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,"wheat/rye (bread, pasta, baked goods)",1.5700,14.80,7.1600,0.003850,647.500,33385.600
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,peas,0.9800,5.90,7.5200,0.007460,396.600,27948.200
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,stimulants & spices misc.,0.0000,6.75,0.0000,0.000000,0.000,0.000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,tomatoes,2.0900,7.90,7.5100,0.000800,369.800,5335.700

In [41]:
mapping[mapping["ItemId"] == "I-4524"]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
2006,I-4524,38.0,BEETS GOLDBC,5.0,lb,1.0,lb,PRODUCE,root vegetables,0.43,7.9,1.61,0.00033,28.4,929.2

In [42]:
mapping["CategoryID"].isnull().sum()

np.int64(0)

### Manully Adjust Footprint Factor for Specific Items

In [43]:
# For Manual_Factor: dataframe with items that adjusted GHGe factor manually.
# It takes the id for Manual_Factor for the index being iterated and if it is equal to item id of mapping dataframe then it sets
# the values of the columns to the manually adjusted values
# Note: the values for the columns in mapping DataFrame is adjusted and not Manual_Factor DataFrame
for index, row in Manual_Factor.iterrows():
    itemId = Manual_Factor.loc[index, 'ItemId']
    ghge = Manual_Factor.loc[index, 'Active Total Supply Chain Emissions (kg CO2 / kg food)']
    nitro = Manual_Factor.loc[index, 'g N lost/kg product']
    eutro = Manual_Factor.loc[index, 'Eutrophying Emissions (g PO43-eq / kg food)']
    water = Manual_Factor.loc[index, 'Freshwater Withdrawals (L/FU)']
    land = Manual_Factor.loc[index, 'Land Use (m^2)']
    str_water = Manual_Factor.loc[index, 'Stress-Weighted Water Use (L/FU)']
    mapping.loc[mapping['ItemId'] == itemId, 'Active Total Supply Chain Emissions (kg CO2 / kg food)'] = ghge
    mapping.loc[mapping['ItemId'] == itemId, 'g N lost/kg product'] = nitro
    mapping.loc[mapping['ItemId'] == itemId, 'Eutrophying Emissions (g PO43-eq / kg food)'] = eutro
    mapping.loc[mapping['ItemId'] == itemId, 'Freshwater Withdrawals (L/FU)'] = water
    mapping.loc[mapping['ItemId'] == itemId, 'Stress-Weighted Water Use (L/FU)'] = str_water
    mapping.loc[mapping['ItemId'] == itemId, 'Land Use (m^2)'] = land

In [44]:
mapping.drop_duplicates(subset = ['ItemId'], inplace=True)
mapping.dtypes

ItemId                                                     object
CategoryID                                                float64
Description                                                object
CaseQty                                                   float64
CaseUOM                                                    object
PakQty                                                    float64
PakUOM                                                     object
InventoryGroup                                             object
Food Category_y                                            object
Active Total Supply Chain Emissions (kg CO2 / kg food)    float64
g N lost/kg product                                       float64
Eutrophying Emissions (g PO43-eq / kg food)               float64
Land Use (m^2)                                            float64
Freshwater Withdrawals (L/FU)                             float64
Stress-Weighted Water Use (L/FU)                          float64
dtype: object

In [45]:
mapping.shape

(3173, 15)

In [46]:
mapping

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
0,I-57545,1.0,CHUCK FLAT BONELESS FZN,3.30,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
1,I-10869,1.0,BEEF STIRFRY COV FR,5.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
2,I-7064,1.0,BEEF OUTSIDE FLAT AAA,1.00,Kg,1.0,Kg,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
3,I-37005,1.0,BEEF MEATBALLS,4.54,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
4,I-37002,1.0,BEEF INSIDE ROUND SHAVED,9.00,Kg,1000.0,g,MEAT,beef & buffalo meat,85.5822,329.50,314.8248,0.266786,1716.451,52597.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,I-73854,3.0,"HOT DOG 6"" TWO RIVER",1.00,Kg,1.0,Kg,MEAT,pork (pig meat),12.3100,132.80,76.3800,0.017360,1795.800,66867.400
3172,I-3087,24.0,NOODLES CHOW*MEIN,6.00,BG,5.0,lb,FOOD - GROCERY,"wheat/rye (bread, pasta, baked goods)",1.5700,14.80,7.1600,0.003850,647.500,33385.600
3173,I-4908,18.0,PEAS SUGAR/SNOW CI,10.00,lb,1.0,lb,PRODUCE,peas,0.9800,5.90,7.5200,0.007460,396.600,27948.200
3174,I-75824,54.0,SEASONING TAJIN*CHILI LIME LI,12.00,SM SKR,400.0,g,SPICES,stimulants & spices misc.,0.0000,6.75,0.0000,0.000000,0.000,0.000
3175,I-33643,37.0,"TOMATOES DICED 1/4""",5.00,lb,1.0,lb,PRODUCE,tomatoes,2.0900,7.90,7.5100,0.000800,369.800,5335.700

In [47]:
ingredients = pd.read_csv("data/preprocessed/Ingredients_List.csv")
ingredients

    IngredientId     Qty Uom   Conversion  InvFactor   Recipe
0         I-3421    9.09  Kg  1000.000000     0.5000  P-18863
1         I-5983   18.00   L     1.000000     0.9901  P-18863
2        P-25993   50.00   g     0.001000     2.7503  P-18863
3         I-3642  500.00   g     1.000000   333.3333  P-18907
4         I-6026    1.00  Kg  1000.000000     0.6667  P-18907
..           ...     ...  ..          ...        ...      ...
102       I-4508    5.00   g     0.002205     1.0000  R-75685
103      P-21818    1.00  ea     1.000000     1.0000  R-75685
104      P-35396   90.00   g     1.000000     1.0000  R-75685
105      P-74119  240.00   g     0.001000     1.0000  R-75685
106      P-75383  180.00  ml     0.001000     1.0000  R-75685

[107 rows x 6 columns]

In [48]:
map_list = mapping["ItemId"].unique()
absent_list = []

for item in ingredients["IngredientId"].unique():
    if item not in map_list and item.startswith("I-"):
        absent_list.append(item)

# absent_list contains the IngredientIds that are not present in mapping but are present in the ingredients DataFrame
print(absent_list)

[]

In [49]:
# Converts mapping DataFrame to the Mapping.csv file
path = os.path.join(os.getcwd(), "data", "mapping", "Mapping.csv")
mapping.to_csv(path, index = False, header = True)

In [50]:
mapping[mapping["ItemId"] == "I-19143"]

,ItemId,CategoryID,Description,CaseQty,CaseUOM,PakQty,PakUOM,InventoryGroup,Food Category_y,Active Total Supply Chain Emissions (kg CO2 / kg food),g N lost/kg product,Eutrophying Emissions (g PO43-eq / kg food),Land Use (m^2),Freshwater Withdrawals (L/FU),Stress-Weighted Water Use (L/FU)
674,I-19143,21.0,CHIA SEEDS BLACK ORGANIC,5.0,Kg,1000.0,g,SPICES,other grains/cereals,1.916667,5.9,7.473333,0.004796,448.533333,21011.7